### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#1]
First: very impressive solution! Thanks.

The game isn't able to scale correctly on screens with a different aspect ratio than 4:3 which was default back then (noticeable e.g. at the countdown traffic lights at the beginning of every race). It would be great to have an option to enforce the original aspect ratio when playing in full screen.

**Comment by zaps166** [comment]
Thanks!
It is a good idea, it will be available in configuration file soon.

PS.: Do you play on Linux or Windows? Is it enough stable?

**Comment by zaps166** [comment]
Sorry for the delay, fixed!

//The conversation was continued on e-mail.
