### ISSUE TITLE
"MOVIE FILE NOT FOUND" error

### ISSUE THREAD

**Issue by astronos2007** [zaps166/NFSIISE#10]
Hi! I compiled the game succesfully, copied all the data files within the folder and renamed to lowercase. Now, when I start the game, it says "MOVIE FILE NOT FOUND", with only an abort option left. Did I do something wrong?

**Comment by zaps166** [comment]
Hi! Probably something is wrong with the data (especially with `fedata` directory). Be sure that everything is lower case (maybe script doesn't convert everything?). Be sure that you have permissions (script should also do it) and be sure that you habe data from NFSIISE (Special Edition), not from NFSII. See #6 for more information (e.g. for correct directory structure).

**Comment by astronos2007** [comment]
You were right! I put the NFS II contents, instead of NFS II SE. It works like a charm now, thank you! :+1:

**Comment by zaps166** [comment]
Ok!

**Comment by josefnpat** [comment]
haha, had the same issue. Is the NFSII vs NFSIISE string detectable?
