### ISSUE TITLE
Add support for cockpits

### ISSUE THREAD

**Issue by MeliusCZ** [zaps166/NFSIISE#100]
I know it's not supported but it would be nice to be able to get data from the original NFS2 to see cockpits of the vehicles.

**Comment by ivanodintsoff** [comment]
I think that's because the accelerated version which this version is based does not show the cockpit even in the original. Would be nice to run the non-accelerated version though.

**Comment by zaps166** [comment]
See [this](https://github.com/zaps166/NFSIISEN)

**Comment by kenderipa** [comment]
@zaps166, would it be possible to mod the cockpit in somehow? I mean, from my layman's perspective it may be a compiling flag :)
