### ISSUE TITLE
Lag issue while playing

### ISSUE THREAD

**Issue by ttanderr** [zaps166/NFSIISE#102]
I did exactly like in this video https://www.youtube.com/watch?v=IxJryhmvF0I, but when I start playing in the race (not in te menu), it just has a "jump lag" every 5 seconds or so. I tried it on Windows 11.

**Comment by ttanderr** [comment]
Okay, the lag issue was occured because of the V-sync, I just limited the Hz of my screen (I had 165 Hz and I put it on 60 Hz) and that solved the problem.

**Comment by ttanderr** [comment]
I put it back on 165 Hz and in the "open_config" file I changed the V-sync and put VSync=3,3. now it runs at 55 FPS with no lag issues!

**Comment by zaps166** [comment]
`VSync` is an integer, so it's `3`, not `3,3`.
IIRC this game has fixed 64 FPS, so runs smoothest on n*64 Hz.
I haven't got any lags on 144 Hz (Linux/X11).
