### ISSUE TITLE
Question about the stf files in .nfs2se/stats/

### ISSUE THREAD

**Issue by vgarcia007** [zaps166/NFSIISE#103]
Sorry for posting this as an issue. But i dont know how to reach out otherway.

Has someone thinkered with the stf files in .nfs2se/stats/

The Playernames are in clear text but the lap times are encrypted somehow.

My goal ist to make an online Service where everyone can upload there lap times and compair it.

Maybe someone knows more about the file format of this files?

**Comment by zaps166** [comment]
Anyway STF file is handled in C code, here: https://github.com/zaps166/NFSIISE/blob/d724a4ec7e8ea95eacb6f5072039ca0872fd2cc6/src/FetchTrackRecords.c#L25
