### ISSUE TITLE
Error while launching

### ISSUE THREAD

**Issue by kenderipa** [zaps166/NFSIISE#107]
Hello,

I have a following error after launching the game, following intro movie and loading screen:

ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pipewire.so (/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pipewire.so: cannot open shared object file: No such file or directory)
Application closed with a signal: 11
Segmentation fault

Debian Trixie, JWM, nVidia proprietary, Pipewire.

Any ideas?

**Comment by zaps166** [comment]
you need to install 32-bit pipewire library

**Comment by kenderipa** [comment]
Thanks! Which one, though?

**Comment by kenderipa** [comment]
I've installed all i386s beginning with libpipewire, that didn't help.

**Comment by zaps166** [comment]
What error you have now?

**Comment by zaps166** [comment]
Do you use my package from github or it's compiled from sources or it's different package?

**Comment by kenderipa** [comment]
> What error you have now?

Same one.

> Do you use my package from github or it's compiled from sources or it's different package?
Your package from Github.

**Comment by zaps166** [comment]
> Your package from Github.

Tested now, it's working for me on Manjaro (pipewire), so package is ok.

You need 32-bit OpenGL drivers (nvidia), and 32-bit pipewire for audio. Did you copy correctly `gamedata` and `fedata` with r/w rights and small letters?

**Comment by kenderipa** [comment]
> > Your package from Github.
> 
> Tested now, it's working for me on Manjaro (pipewire), so package is ok.
> 
> You need 32-bit OpenGL drivers (nvidia), and 32-bit pipewire for audio. Did you copy correctly `gamedata` and `fedata` with r/w rights and small letters?

I tried it on Windows a couple of months ago, it worked. Now I've used your capitalization script to decapitalize files and folders and give the correct permissions.

**Comment by kenderipa** [comment]
Just tried installing alsa-utils:i386, didn't help.

**Comment by zaps166** [comment]
In Arch Linux it's `lib32-pipewire`.

**Comment by kenderipa** [comment]
sudo apt install libpipewire-0.3-0:i386 libpipewire-0.3-common:i386 libpipewire-0.3-dev:i386 libpipewire-0.3-modules:i386 libpipewire-0.3-modules-x11:i386

$ ./nfs2se
Need For Speed II SE
  Wrapper v1.3.0
  Game    v1.1.2
  OpenGL  1
ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pipewire.so (/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pipewire.so: cannot open shared object file: No such file or directory)
Application closed with a signal: 11
Segmentation fault

**Comment by zaps166** [comment]
How about pipewire-alsa?

**Comment by kenderipa** [comment]
Yeah, it was game data problem. I've backed up game files on Windows, and looks like that while dragging and dropping Windows loses some files (966 by dragging and dropping, 1010 after Ctrl+C, Ctrl+V). The game launches now. Sorry for wasting your time.

**Comment by zaps166** [comment]
Ok, good, but do you have sound?

**Comment by kenderipa** [comment]
> Ok, good, but do you have sound?

Yes I do.
