### ISSUE TITLE
[SOLVED] 'MOVIE FILE NOT FOUND' after launching the game

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [zaps166/NFSIISE#11]
[Bug]
After following your installation guide (compile, copy game data, convert to lowercase) the game keeps letting me know: 'MOVIE FILE NOT FOUND'  after starting it.

Using Arch Linux x64

PS: Many thanks for your engine!

**Comment by zaps166** [comment]
Hi!
Again :smiley:
See: #10 and #6

Btw. are you using AUR package?

**Comment by cRaZy-bisCuiT** [comment]
Nop, GIT directly. Sorry and thanks for the instant replay. I'll have a look!

**Comment by cRaZy-bisCuiT** [comment]
tree
.
├── art
│   ├── credits.qfs
│   ├── epost.qfs
│   ├── f355.qfs
│   ├── ferr.qfs
│   ├── fpost.qfs
│   ├── gpost.qfs
│   ├── gt1.qfs
│   ├── gt90.qfs
│   ├── hisfer.qfs
│   ├── hisfrd.qfs
│   ├── hisisd.qfs
│   ├── hisita.qfs
│   ├── hisjag.qfs
│   ├── hisltus.qfs
│   ├── hismac.qfs
│   ├── indigo.qfs
│   ├── info.qfs
│   ├── ipost.qfs
│   ├── isdera.qfs
│   ├── ital.qfs
│   ├── jag.qfs
│   ├── lotus.qfs
│   ├── mac.qfs
│   ├── main.qfs
│   ├── modem.qfs
│   ├── mouse.fsh
│   ├── mus.qfs
│   ├── nazca.qfs
│   ├── network.qfs
│   ├── record.qfs
│   ├── sldshow.qfs
│   ├── slides
│   │   ├── sld355f.qfs
│   │   ├── sld355f2.qfs
│   │   ├── sld355f3.qfs
│   │   ├── sld355f4.qfs
│   │   ├── sld355f5.qfs
│   │   ├── sld355f6.qfs
│   │   ├── sld355f7.qfs
│   │   ├── sld355f8.qfs
│   │   ├── sldblk.qfs
│   │   ├── sldbra.qfs
│   │   ├── sldfer.qfs
│   │   ├── sldfer2.qfs
│   │   ├── sldfer3.qfs
│   │   ├── sldfer4.qfs
│   │   ├── sldfer5.qfs
│   │   ├── sldfer6.qfs
│   │   ├── sldfer7.qfs
│   │   ├── sldfer8.qfs
│   │   ├── sldfrd.qfs
│   │   ├── sldfrd2.qfs
│   │   ├── sldfrd3.qfs
│   │   ├── sldfrd4.qfs
│   │   ├── sldfrd5.qfs
│   │   ├── sldfrd6.qfs
│   │   ├── sldfrd7.qfs
│   │   ├── sldfzr.qfs
│   │   ├── sldgt1.qfs
│   │   ├── sldgt12.qfs
│   │   ├── sldgt13.qfs
│   │   ├── sldgt14.qfs
│   │   ├── sldgt15.qfs
│   │   ├── sldgt16.qfs
│   │   ├── sldgt17.qfs
│   │   ├── sldgt18.qfs
│   │   ├── sldind.qfs
│   │   ├── sldind2.qfs
│   │   ├── sldind3.qfs
│   │   ├── sldind4.qfs
│   │   ├── sldind5.qfs
│   │   ├── sldind6.qfs
│   │   ├── sldind7.qfs
│   │   ├── sldind8.qfs
│   │   ├── sldisd.qfs
│   │   ├── sldisd2.qfs
│   │   ├── sldisd3.qfs
│   │   ├── sldisd4.qfs
│   │   ├── sldisd5.qfs
│   │   ├── sldisd6.qfs
│   │   ├── sldisd7.qfs
│   │   ├── sldisd8.qfs
│   │   ├── sldita.qfs
│   │   ├── sldita2.qfs
│   │   ├── sldita3.qfs
│   │   ├── sldita4.qfs
│   │   ├── sldita5.qfs
│   │   ├── sldita6.qfs
│   │   ├── sldita7.qfs
│   │   ├── sldita8.qfs
│   │   ├── sldjag.qfs
│   │   ├── sldjag2.qfs
│   │   ├── sldjag3.qfs
│   │   ├── sldjag4.qfs
│   │   ├── sldjag5.qfs
│   │   ├── sldjag6.qfs
│   │   ├── sldjag7.qfs
│   │   ├── sldjag8.qfs
│   │   ├── sldmac.qfs
│   │   ├── sldmac2.qfs
│   │   ├── sldmac3.qfs
│   │   ├── sldmac4.qfs
│   │   ├── sldmac5.qfs
│   │   ├── sldmac6.qfs
│   │   ├── sldmac7.qfs
│   │   ├── sldmac8.qfs
│   │   ├── sldmus.qfs
│   │   ├── sldmus2.qfs
│   │   ├── sldmus3.qfs
│   │   ├── sldmus4.qfs
│   │   ├── sldmus5.qfs
│   │   ├── sldmus6.qfs
│   │   ├── sldmus7.qfs
│   │   ├── sldmus8.qfs
│   │   ├── sldnaz.qfs
│   │   ├── sldnaz2.qfs
│   │   ├── sldnaz3.qfs
│   │   ├── sldnaz4.qfs
│   │   ├── sldnaz5.qfs
│   │   ├── sldnaz6.qfs
│   │   ├── sldnaz7.qfs
│   │   ├── sldnaz8.qfs
│   │   ├── sldv8.qfs
│   │   ├── sldv82.qfs
│   │   ├── sldv83.qfs
│   │   ├── sldv84.qfs
│   │   ├── sldv85.qfs
│   │   ├── sldv86.qfs
│   │   ├── sldv87.qfs
│   │   └── sldv88.qfs
│   ├── spost.qfs
│   ├── title.qfs
│   ├── track
│   │   ├── lastrec.qfs
│   │   ├── lrtinfo.qfs
│   │   ├── medinfo.qfs
│   │   ├── medrec.qfs
│   │   ├── monoinfo.qfs
│   │   ├── monorec.qfs
│   │   ├── mystinfo.qfs
│   │   ├── mystrec.qfs
│   │   ├── nortinfo.qfs
│   │   ├── nortrec.qfs
│   │   ├── ovalinfo.qfs
│   │   ├── ovalrec.qfs
│   │   ├── ozinfo.qfs
│   │   ├── ozrec.qfs
│   │   ├── pacinfo.qfs
│   │   └── pacrec.qfs
│   ├── victory.qfs
│   └── wpost.qfs
├── config
│   ├── config.dat
│   ├── hudcon.dat
│   ├── platcfg.dat
│   └── temp.txt
├── movies
│   ├── demo.0
│   ├── demo.1
│   └── demo.2
├── save
│   └── temp.txt
├── stats
│   ├── last.ssf
│   ├── last.stf
│   ├── med.ssf
│   ├── med.stf
│   ├── mono.ssf
│   ├── mono.stf
│   ├── myst.ssf
│   ├── myst.stf
│   ├── nort.ssf
│   ├── nort.stf
│   ├── oval.ssf
│   ├── oval.stf
│   ├── oz.ssf
│   ├── oz.stf
│   ├── pac.ssf
│   ├── pac.stf
│   └── prh
│       ├── bprh01.ssf
│       ├── bprh01.stf
│       ├── bprh02.ssf
│       ├── bprh02.stf
│       ├── bprh03.ssf
│       ├── bprh03.stf
│       ├── bprh04.ssf
│       ├── bprh04.stf
│       ├── bprh05.ssf
│       ├── bprh05.stf
│       ├── bprh06.ssf
│       ├── bprh06.stf
│       ├── bprh07.ssf
│       ├── bprh07.stf
│       ├── bprh08.ssf
│       ├── bprh08.stf
│       ├── prh01.ssf
│       ├── prh01.stf
│       ├── prh02.ssf
│       ├── prh02.stf
│       ├── prh03.ssf
│       ├── prh03.stf
│       ├── prh04.ssf
│       ├── prh04.stf
│       ├── prh05.ssf
│       ├── prh05.stf
│       ├── prh06.ssf
│       ├── prh06.stf
│       ├── prh07.ssf
│       ├── prh07.stf
│       ├── prh08.ssf
│       └── prh08.stf
└── text
    ├── fixed14.ffn
    ├── swiss13.ffn
    ├── swiss16.ffn
    ├── swiss18.ffn
    ├── swiss24.ffn
    ├── swiss36.ffn
    ├── swiss36a.ffn
    ├── text.eng
    ├── text.fre
    ├── text.ger
    ├── text.ita
    ├── text.met
    ├── text.spa
    └── text.swe

**Comment by cRaZy-bisCuiT** [comment]
It might still be my fault due to wrong named game files (it's not SE even if stated maybe). I'll try another source. Sorry for the inconvinience. I'll report back

**Comment by zaps166** [comment]
Movies have `*.dct` extension (I can't see it in your tree). I can see only `demo.*` movies. Correct tree is here (https://github.com/zaps166/NFSIISE/issues/6#issuecomment-223326983).

**Comment by cRaZy-bisCuiT** [comment]
It was my fault, the correct files fixed this issue. Now I get a black screen after launching and nothing happens. Looking for a fix here for this issue.

**Comment by zaps166** [comment]
Ok, closing.
If you can't fix the issue then report it :)

**Comment by zaps166** [comment]
And also if you fix the issue you can write here what was wrong :smile:

**Comment by slrslr** [comment]
I had same problem, but after downloading torrent magnet:?xt=urn:btih:7375613e21b6616d33286ddf6844fa273c85ddad , moved GameData, FeData (part of the torrent) directories, run script "convert_to_lowercase", it started working.

**Comment by z2z** [comment]
https://github.com/z2z/misc/raw/master/TITLEAV.DCT 

Copying above file in fedata\pc\movies folder fixes the issue for Win10 in NFS2SE Rip Edition
