### ISSUE TITLE
[Linux Mint DE 6] Works like butter but no audio

### ISSUE THREAD

**Issue by Ligutrino** [zaps166/NFSIISE#110]
Hi, zaps166.

I have no audio, no music, no engines, nothing. Configuration and game works perfectly.

I'm running LMDE 6 and the portable fourth release of the wrapper (nfs2se). I have the 32bit packages installed.

I have 4 audio output devices, but all the other programs output on the right device. My monitor's jack output from the DP port of the RX6600 XT, Topping DAC analog (default out) and S/PDIF, and Realtek S/PDIF. For the moment I can't test the S/PDIF outputs, but both analog doesn't emit a sound.

What am I missing?

EDIT:
Need For Speed II SE
  Wrapper v1.3.0
  Game    v1.1.2
  OpenGL  1
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pipewire.so (/lib/i386-linux-gnu/alsa-lib/libasound_module_pcm_pipewire.so: cannot open shared object file: No such file or directory)

I have libasound2.i386 so I don't now what package i'm missing.

Best regards.

**Comment by Ligutrino** [comment]
Thank you zaps166,

sudo apt install pipewire-alsa:i386 fixed the audio!

For some reason this packages are not listed on Synaptic.

**Comment by zaps166** [comment]
Good to hear it's working now!
