### ISSUE TITLE
Help compiling APK

### ISSUE THREAD

**Issue by brunoooh** [zaps166/NFSIISE#111]
Hi and thank you for doing this, I've been trying to run this old favorite game of mine on Android through emulators without success for a while.. BUT I haven't got the necessary skills/knowledge to compile the APK on my own.

Could you please provide a step by step instruction on how to compile the Android version ? 

I own the original game so I have the needed files, but I just don't know what I should do with them and your files to produce a working APK.

Or maybe (since the game seems to be considered abandonware), you might share a link to an already compiled file made by someone ?

Thanks a lot

**Comment by zaps166** [comment]
Last work on Android was 6 years ago. I guess new toolchain will not compile it. Also it doesn't have any touchscreen support - you need mouse+keyboard or gamepad to paly on Android.

Compiling it now with new toolchain will need rework, so it's not that easy.

I have somewhere old unsigned APK, but it doesn't work to me on new phone (looks like missing write permissions or...?).

best would be some day to port it to 64-bit, Vulkan, touchscreen and widescreen :smile:

**Comment by brunoooh** [comment]
Thank you so much !
I'll tell you what happen when I'll try.

I really would love it if you manage to recompile it, if I can provide any help please let me know : I'd be glad to help in anyway I can

**Comment by brunoooh** [comment]
Hi, unfortunately my try failed : I get an error message saying "Probably crash !" and "Application closed with a signal 11"
Maybe that error code will tell you what I should do ?

**Comment by zaps166** [comment]
Hmm, I don't know. Maybe I have to build a new APK :smile: 

Signal 11 is just crash (SIGSEGV).

What will happen i when you remove `/sdcard/NFSIISE` - do you have crash or message about missing data?

**Comment by brunoooh** [comment]
> Hmm, I don't know. Maybe I have to build a new APK 😄
>
🙏🙏🙏

> Signal 11 is just crash (SIGSEGV).
> 
> What will happen i when you remove `/sdcard/NFSIISE` - do you have crash or message about missing data?

The error mrssages gets much simpler to understand if I do that : "can't find "gamedata" and/or "fedata" directories in current working directory !"

**Comment by zaps166** [comment]
> The error message gets much simpler to understand if I do that : "can't find "gamedata" and/or "fedata" directories in current working directory !"

Maybe it can see directories, but can't read files (no permissions). The last thing: Go to application information in Android and grant all permissions manually. Many devices allows to go to information by tap-and-hold and popup menu. If not, find applications in Android settings and find this app.

**Comment by brunoooh** [comment]
> Maybe it can see directories, but can't read files (no permissions). The last thing: Go to application information in Android and grant all permissions manually. Many devices allows to go to information by tap-and-hold and popup menu. If not, find applications in Android settings and find this app.

I've just checked : the only permission was storagec access and it was already on.

**Comment by zaps166** [comment]
I've managed to compile with new toolchain and run this game on new phone with Android 13. I'll push changes when I finish it.

**Comment by brunoooh** [comment]
Whoohoo ! That's wonderful news !!

**Comment by zaps166** [comment]
Could you try this: [NFSIISE-debug-02.03.2024-18.40.apk.zip](https://github.com/zaps166/NFSIISE/files/14470251/NFSIISE-debug-02.03.2024-18.40.apk.zip) ?

From the updated README:
> On Android devices, copy gamedata, fedata, install.win, text.*, nfs2se.conf.template into /sdcard/NFSIISE or /storage/emulated/0/NFSIISE (create NFSIISE directory first).

**Comment by brunoooh** [comment]
I got "cannot open configuration file "nfs2se.conf"

**Comment by zaps166** [comment]
Do you have all required files in `/sdcard/NFSIISE` including `nfs2se.conf.template`, `install.win`, `text.*`?

**Comment by brunoooh** [comment]
Nope, I'll I forgot to add them, I just put both folders from the original game, I'll try that in a few minutes

**Comment by brunoooh** [comment]
Ok, I've downloaded every file from the "Need For Speed II SE" folder on your github page and put them in the NFSIISE folder on my phone alongside the 2 folders from the original game... no more error message, but a black screen. Did I forgot some other files ?

**Comment by zaps166** [comment]
Used [Termux](https://play.google.com/store/apps/details?id=com.termux)
Command: `find /sdcard/NFSIISE > /sdcard/files.txt`

[files.txt](https://github.com/zaps166/NFSIISE/files/14470496/files.txt)

Btw. Does it work on PC?

**Comment by brunoooh** [comment]
Er... I didn't understand your last message (sorry probably my poor english's fault), what did you mean about Termux ?

And are you asking me to try the game on Windows ?

**Comment by zaps166** [comment]
I mean, I used Termux to generate file tree. Look at attached `files.txt`, you'll see file structure.

> And are you asking me to try the game on Windows ?

Windows or Linux - maybe your data are incorrect?

**Comment by brunoooh** [comment]
ok, so I've got the same files, in the same place and unfortunately I get a black screen when launching the game

And yes the original game works on Windows (I used the same file in a dosbox pure emulator and the game plays just fine both 3dfx and DirectX versions)

**Comment by zaps166** [comment]
> And yes the original game works on Windows (I used the same file in a dosbox pure emulator and the game plays just fine both 3dfx and DirectX versions)

Could you download `nfs2se-win32.zip` from https://github.com/zaps166/NFSIISE/releases and check this on Windows?

**Comment by brunoooh** [comment]
works perfectly on windows, so I took the same files to the phone  (in case my previous copy was corrupted) and still got black screen :(

not sure what it means, but after opening the game getting the black screen, if the phone goes to sleep and I unlock it, it's still the black screen of course, but the virtual keyboard pops up

**Comment by brunoooh** [comment]
ok so I've got very good news : I've copied the files from my old phone (where the game works) to my new phone... and now it works there too !!

well almost : on the old phone I could manage the mouse pointer with the touch screen and use the game menu to select a track a car and then launch the race. On my current phone (Android 13) the game gets to the menu and then the menu keeps rolling as if I was pressing the down key all the time.

I'm going to connect a joystick or keyboard and try again.

I've notice some weird behavior when trying to force game end through the android keys (show all apps, close all) : a message appears telling how much memory has been freed, but the game is still runnin (engine sound can be heard) and I have to close again a few times before the app is really closed

I've got a last side question : when I run the game with your modifications (both windows and android) the view is from inside the car (I don't see my own car), on the original game, the players car is on screen, is it a setting that you changed on purpose or something I should change from the menu (I haven't search a lot for now) ?

**Comment by zaps166** [comment]
Good that's finally working!

> I've got a last side question : when I run the game with your modifications (both windows and android) the view is from inside the car (I don't see my own car)

Change camera view ("C" button by default).

> the game gets to the menu and then the menu keeps rolling as if I was pressing the down key all the time.

It uses accelerometer as a gamepad, try to put phone on a desk with screen up and keep phone in this position. I can disable this behavior, but with this it's possible to assign keys in game menu and play by tilting phone :sweat_smile:

**Comment by zaps166** [comment]
Updated package to d48f64c08cdcf32e6d9875133fc1b4138f926dc0 (could you test?): [NFSIISE-debug-02.03.2024-22.30.apk.zip](https://github.com/zaps166/NFSIISE/files/14470829/NFSIISE-debug-02.03.2024-22.30.apk.zip)

**Comment by brunoooh** [comment]
I'm going to test right now :)

I had found the "C" key for the camera in the meantime (I was playing on the windows version to explore options)... but how can I simulate pressing the "c" key on android ? I suppose I can plug a keyboard once and change view by pressing C, on the windows version I noticed the changes are kept the next time you open the game

**Comment by zaps166** [comment]
You can assing a gamepad key for camera view in game settings.

I have a bit motivation to do some improvements, so maybe I'll improve gamepad in this game!

**Comment by brunoooh** [comment]
It seems just perfect !! Thank you so much !

I'played with bluetooth keyboard and then bluetooth gamepad and it worked just fine ;)

I've noticed than the controls are more accurate with the keyboard, but that's nowhere near limiting my joy of playing the game. Once again, thank you so much for what you've done :)

**Comment by brunoooh** [comment]
> I have a bit motivation to do some improvements, so maybe I'll improve gamepad in this game!

I have no idea about how are it is to do, but... what about an on screen virtual gamepad ?

**Comment by zaps166** [comment]
That's new APK: [NFSIISE-debug-03.03.2024-23.14.apk.zip](https://github.com/zaps166/NFSIISE/files/14474817/NFSIISE-debug-03.03.2024-23.14.apk.zip)

Changes:
- you can use touchscreen as a touchpad to move mouse cursor
- tap-and-hold presses RETURN key
- back button presses ESC key
- fixed issue with bad image scaling (happened from time to time)
- download the newest `nfs2se.conf.template` from master branch and rename it to `nfs2se.conf` (`nfs2se.conf.template` is no longer used on Android!)
- you can disable accelerometer as joystick in `nfs2se.conf` (don't forget to update this file!) - remove `#` from `AccelerometerAsJoystick` line and set it to `0` - it will no longer "keeps rolling as if I was pressing the down key all the time" when your phon is in various positions

> what about an on screen virtual gamepad ?

That's too much for now, maybe someday... :smile:

**Comment by brunoooh** [comment]
Thanks again for your fantastic work. I will try the latest APK as soon as possible.
One final question : would you agree/be interested in your work being turned into a Retroarch core ? I know someone who's been thinking about making a core for NFSIISE...

**Comment by zaps166** [comment]
> Retroarch

I don't know this project, hmm.

**Comment by brunoooh** [comment]
https://www.retroarch.com/

Besides old computers and consoles, RA also allows old PC games to run on modern hardware

Let me know if you are interested

**Comment by zaps166** [comment]
> Let me know if you are interested

What I should do? Maybe just make a script and prepare config file to run it there?

**Comment by brunoooh** [comment]
Well I'm not the right person to answer that question, so I've asked the one I mentioned earlier to join the conversation. Hopefully it will work out :)

**Comment by zaps166** [comment]
Now you can download [released ZIP](https://github.com/zaps166/NFSIISE/releases/tag/v1.4.0) for Android, many things has been improved!

**Comment by brunoooh** [comment]
Thank you so much, I will try this today and send the link to my RetroArch contact :)

**Comment by brunoooh** [comment]
![20240317_095255](https://github.com/zaps166/NFSIISE/assets/50417948/01764f6d-6921-4216-ad77-5efe382937c3)

Everything runs smoothly... but I get this error message each time I launch the app. I just press on OK and the game works perfectly

**Comment by zaps166** [comment]
`nfs2se.conf` or `nfs2se.conf.template`? You need `nfs2se.conf` (as in ZIP). Remove the old file and copy new from ZIP. It's working good on my 3 phones :smile:

**Comment by brunoooh** [comment]
Oopsy, I had so many folders due to testing ealier versions, I moved the files from the zip to the wrong place and ran the new apk with the old files.
No more error message once the new files were put in the right place
