### ISSUE TITLE
Feature request: Use DPAD (HAT/POV)

### ISSUE THREAD

**Issue by sonik-br** [zaps166/NFSIISE#116]
I'm not sure if it's already possible but I could not get the DPAD to register in game.
I've seen that it's now possible to map buttons for menu navigation. Would be handy to use the DPAD for this.

**Comment by zaps166** [comment]
Are you able to assign it in game for e.g. steering?

**Comment by sonik-br** [comment]
No, the DPAD does not register at all on the game's setup.

**Comment by zaps166** [comment]
Is it the Logitech Wheel? I have to check it on Windows, because I think I was able to assign DPad as regular button on Linux.

**Comment by sonik-br** [comment]
Tested with a logitech wheel and a xbox one controller too

**Comment by zaps166** [comment]
Ok, I'll check this
