### ISSUE TITLE
Compilation error due to SDL2 not updated

### ISSUE THREAD

**Issue by pachecogonzalo** [zaps166/NFSIISE#118]
Following the installation steps for Linux. when compiling on Ubuntu 22.04, I got an error on DInput.c line 238:
...NFSIISE/src/DInput.c:238: undefined reference to `SDL_JoystickPathForIndex'

I am no expert, but I searched a little bit and found that the installed package libsdl2-dev:i386 is version 2.0, and the function SDL_JoystickPathForIndex belongs to a newer version of SDL.
I tried to install the updated version of SDL, but since I had no luck. How do you install the required version? I compiled the SDL lib and got it installed elsewhere (although folowing instructions from here https://wiki.libsdl.org/SDL2/Installation), so the workaround I used was to comment the block in DInput.c where the function was, and it worked.
The downside is that my joystick is not detected (a Logitech F310).
I also tried to modify the compile script to include the path of this library, but I must have got something wrong and had no luck either.

Do you have a guide to install the newer version of SDL, to have a successfull install?
Kind regards

**Comment by zaps166** [comment]
You have too old SDL2. It's problem for all non-rolling release Linux distributions to have obsolete libraries.

Simple way: Go [here](https://github.com/zaps166/NFSIISE/releases) and download for Linux. That's what this package is for.

You can compile SDL2, too, but it requires minimum knowledge.
[Download](https://github.com/libsdl-org/SDL/releases/download/release-2.30.2/SDL2-2.30.2.tar.gz) source code, unpack. Install all required tools and libraries (on Ubuntu with `-dev` suffix) to compile SDL2. Run `./configure` and `make -j$(nproc)` and `sudo make install`. Next modify `compile_nfs` to provide SDL2 include and libs paths from `/usr/local` and run compilation (I guess you have to append `-I/usr/local/include -L/usr/local/lib` after `$CC`).

**Comment by pachecogonzalo** [comment]
It works perfectly, many thanks!
