### ISSUE TITLE
No anti-aliasing with `gl2`

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#122]
Hello,
I'm still stuck on the `gl1` compile switch. When I remove it (and thus implzitly use gl2) then I get no anti-aliasing, although it is configured in the config. When I switch to `gl1` then it works.

I've compiled the binary using [my build environment](https://github.com/thomas-mc-work/nfsiise-build-env) for Ubuntu 24.04

Can I provide something for debugging?

**Comment by zaps166** [comment]
Unsupported: https://github.com/zaps166/NFSIISE/blob/529ed15ad1b2e9fe173dfcac0a4dee61d12b8833/Need%20For%20Speed%20II%20SE/nfs2se.conf.template#L21

**Comment by thomas-mc-work** [comment]
Thanks!
