### ISSUE TITLE
it's running to fast, some physic are not right

### ISSUE THREAD

**Issue by Dennis50300** [zaps166/NFSIISE#126]
https://www.youtube.com/watch?v=_o10HGqd3lU
you can see the game is partly running too fast, i think an FPS_Cap could help

when i got pause, at race you see it, because the camera around the car is "escalating" :-)

is there a option to limit fps, max to 60 or so or 30 ?
This world really help, a typical voodoo2 accelerator, timeturely don't pushing more than 60 fps and there must be something coupled with the FPS and or hzfrequency typical to this time
i think, my monitor at this time was running with 60hz or max then 85Hz :D 

best regards

**Comment by zaps166** [comment]
Internally this game runs in about 64 FPS - it has timer for this (except e.g. rotating camera on pause).

If you run on default settings, V-Sync should be enabled. To limit FPS even more, set `VSync=2` in `$HOME/.nfs2se/nfs2se.conf` to achieve half of the screen refresh rate.

You can try external frame limiters, too (e.g. mangohud), but remember this is 32-bit.

**Comment by Dennis50300** [comment]
ah ok, yes ingame setting would be best way
on windows we can use the drivers, thats ok too, but the nvidia-driver in my opinion on Linuxdistributions haven't these settings
i have a 165hz Monitor, but set it on 120hz on the system, hope then with vsync=2 it gets half of this
it could sync from 48 to 165 fps (gsync/freesync, also gsync-compatible)
i try and see "oh, nice" msaa and some other nice things :-)

i come again to report

best regards

**Comment by Dennis50300** [comment]
oh yeah, now its no more running to fast and look better with MSAA
another Physics thing is, on the back of the Mclaren F1, the Spoiler, if it's running to fast, you can't see that it's getting up and down, it is only up or down
now you can see this, like at the time this games was not so old, it's driving more right and feels more better, not so much cpulimits what makes inputdelays (for this old game :D :P )
the camera in Pause, are not escalating crazy, so the Problem is fixed with `Vsync=2`

really great

"glide" retro greetings from germany
:-)
