### ISSUE TITLE
Why pull nfs2se-obj from sourceforge?

### ISSUE THREAD

**Issue by ProfessorKaos64** [zaps166/NFSIISE#13]
I didn't know how else to ask this. URL="http://zaps166.sourceforge.net/downloads/nfs2se-obj" ... why can't this be included in the repository?

**Comment by zaps166** [comment]
I'll think about better solution, because now it is just a wrapper. Maybe another git repo for disassembly as a dependency?

**Comment by ProfessorKaos64** [comment]
Maybe that would work, just a thought. I would think managing two locations would be harder. You could add the repo or repo folder here as a sub module.

**Comment by ProfessorKaos64** [comment]
Thank you!

**Comment by zaps166** [comment]
:smile: I hope it works properly :)

**Comment by ProfessorKaos64** [comment]
I'll test when I'm back from vacation. If not, i'll be sure to report back.

**Comment by zaps166** [comment]
Ok (I've already tested due to AUR package update) :)
I want to fix one more bug and do a stable release.

> I'll test when I'm back from vacation

Have fun!

**Comment by ProfessorKaos64** [comment]
I noticed that you commented out DEBUG_ASM, but use it in Linux build steps. Is this intentional?

**Comment by zaps166** [comment]
Fixed :smile:

**Comment by ProfessorKaos64** [comment]
Debian package builds ok. Hopefully this week I will get to refining it and testing the game data etc.

**Comment by zaps166** [comment]
I think I'll release "stable" soon.

**Comment by zaps166** [comment]
> I think I'll release "stable" soon.

Released v1.1.0 (you can use dources for package from the release from GitHub)!

**Comment by ProfessorKaos64** [comment]
Sweet, thanks. Wrapping my head around building rpcs3 at the moment, but testing this out is next after that I hope (I get distracted at times ^_^)
