### ISSUE TITLE
Run game without X server

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#19]
Will it be posible to make the game run without a X server? At the moment it's aborting with an error message: `SDL_Init failed: No available video device`.

**Comment by zaps166** [comment]
The question is about my binary or about the source code?

**Comment by zaps166** [comment]
My binary available on GitHub works only on X11 (static SDL2), but the game can run on Wayland (or on any other technology supported by SDL2). I've just tried on Intel graphics and Wayland - it works, but the game can't fill the entire screen in my case (only 640x480, left-bottom rect). Also I don't know how to enable triple-buffer (probably disabled, but I don't know Wayland :smile:)

**Comment by thomas-mc-work** [comment]
> The question is about my binary or about the source code?

Eventually on the binary, but the solution needs to be in either the code or more probably lies in the SDL dependency. I've read that it's possibly to utilize the frame buffer device or similar like described here: http://stackoverflow.com/a/3703044

This would be great for an HTPC that doesn't need to run a X server.

**Comment by zaps166** [comment]
If you compile it manually (don't use my binary which uses only X11) you can try to run it on DirectFB, but I've never used this (game currently uses old OpenGL 1.x).
