### ISSUE TITLE
corrupted track record tables

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#2]
I've noticed that some track record tables have corrupted data either showing random strings or nothing like the one attached of Proving Grounds:

![screenshot - 06 03 2016 - 09 40 21](https://cloud.githubusercontent.com/assets/6542498/13553175/36393484-e380-11e5-8b2d-360c87969865.jpg)

There are other tracks that are fine like `North Country` or `Pacific Spirit`.

**Comment by zaps166** [comment]
Hi!
This bug is already fixed (I hope). Please delete all *.stf files from "/home/tomo/.nfs2se/stats".
