### ISSUE TITLE
Binary download from repo

### ISSUE THREAD

**Issue by PPastene** [zaps166/NFSIISE#22]
I wanna try this, but i never compiled a software from source code before. It would be great to offer more detailed instruction about compiling or host the binaries to download

**Comment by zaps166** [comment]
To compile this game you must have full 32-bit environment (as described in `README.md`). Then run compilation script.
Binaries are here: https://github.com/zaps166/NFSIISE/releases

**Comment by PPastene** [comment]
I never compiler a software before, but when i publish this issue i've found the binaries. Thanks anyway
