### ISSUE TITLE
No Audio Stream

### ISSUE THREAD

**Issue by hfte** [zaps166/NFSIISE#24]
I'd finally was able to start the game but i have no audio. Pavucontrol doesn't show a audio stream at all.

Any ideas? 

Thanks for all that work!

**Comment by zaps166** [comment]
Do you use the binary from GitHub or you've compiled it from sources? Which OS? Do you have any errors in console?
`pavucontrol` means that you use PulseAudio - be sure that you have 32-bit pulse audio libraries and also 32-bit ALSA (`libasound`) libraries together with all used plugins (32-bit of course).

**Comment by hfte** [comment]
I use archlinux and installed it via the AUR-Package.

Console showed this:
```
SDL_Init failed: Could not initialize UDEV
ALSA lib dlmisc.c:254:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib32/alsa-lib/libasound_module_pcm_pulse.so
```

After i installed lib32-libpulse and lib32-alsa-plugins i get:
`Application closed with a signal: 11`

**Comment by zaps166** [comment]
Do you use `lib32-sdl2` from repositories or compiled from sources? I don't understand this `SDL_Init failed: Could not initialize UDEV`. Looks like you don't have `lib32-systemd`, but this is required by `lib32-libpulse`. Do you have `lib32-systemd` ?
I also have Arch with `lib32-libpulse` and `lib32-alsa-plugins` and I don't have any problems (maybe I should update package dependencies :smile:)...

**Comment by zaps166** [comment]
If you have any other custom pulseaudio or ALSA plugins - try to install 32-bit libraries for it or try to debug it via GDB - currently no ideas. Also try to run using binary from GitHub (SDL2 statically linked).

**Comment by hfte** [comment]
> Do you use lib32-sdl2 from repositories or compiled from sources? 
I had installed lib32-sdl2 by the repositories. 

> Looks like you don't have lib32-systemd, but this is required by lib32-libpulse. Do you have lib32-systemd ?
The hint witch lib32-systemd was a succes!
I had it installed with lib32-libpulse but it needed a reboot to work fine! :)

> maybe I should update package dependencies 😄
Would be awesome, cause there are people out there which would have already given up :)

Thanks again. Awesome job!

**Comment by hfte** [comment]
Update: Mabye it wasn't the reboot. I still get that crash with a 50% chance when starting the game.

**Comment by zaps166** [comment]
Do you have audio if the game starts w/o crash?

**Comment by hfte** [comment]
If the game is not crashing (only on startup) with
"Probably crash!"
`Application closed with a signal: 11`

then i have audio, and no more issues.

If i uninstall the 32bit audio libraries, then there has never been such a crash, but no audio of course.

**Comment by zaps166** [comment]
Can you debug this (modify AUR package to compile it in debug and don't allow to strip, then use GDB, I can add more info about this if you want to do it)?

**Comment by hfte** [comment]
I give it a try, and write you if i get stuck.

**Comment by zaps166** [comment]
Ok, hint for AUR package: run script with debug argument: `./compile_nfs debug` and add `option=(!strip)` before functions.
