### ISSUE TITLE
View of inside of the car

### ISSUE THREAD

**Issue by AXDOOMER** [zaps166/NFSIISE#27]
I remember when playing this game, I could change the view to the inside of the car by pressing `C`. Isn't it available in the hardware accelerated game? I've only ever played the software rendered version.

**Comment by zaps166** [comment]
Not possible in hardware accelerated game 😞

**Comment by AXDOOMER** [comment]
Is there a way to enable the software rendering? 

I can't remember how it worked back then. I had a voodoo 2, but never got the hardware acceleration to work with this game. Were there two different executable, one for the software rendering and one for the hardware accelerated graphics?

**Comment by zaps166** [comment]
> Is there a way to enable the software rendering?

No, it was a separate executable...
