### ISSUE TITLE
compile error OSX 10.6 w/gcc 4.2.1-apple

### ISSUE THREAD

**Issue by JoshuaPettus** [zaps166/NFSIISE#29]
Hi I got.
Kernel32.c:536:19: error use of undeclared identifier 'TSCBRK'

I noticed there is a new NFSIISE-CPP repository, and that you said it was not as fast as the Assembly version.  Is this mandatory?

Or maybe I need a newer compiler that supports TSCBRK?
Or I can revert that one change you did?  How important is it for OSX?

**Comment by zaps166** [comment]
Hi!

NFSIISE-CPP is only for non-x86 CPUs - no need to use it on x86-CPUs - you'll get slower compilation time, larger binary and slower runtime and possible bugs :)

For macOS please revert: 481f6508a2151ef63f6767c0b4812f28b266eb8a. I'll do `ifdef` later.
