### ISSUE TITLE
app crash on startup

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#3]
The latest trunk version crashes on my machine directly on startup. It only shows a little window with saying "Application closed with a signal: 11". The version from 2016-03-01 was still working.

I'm on Xubuntu 14.04.3 with the binary AMD driver on an AMD A8-5500 APU.

**Comment by zaps166** [comment]
Hmm, could you check which patch causes the crash?

Maybe something is wrong with your data or with config in ~/.nfs2se?

Did you use my precompiled binary?

**Comment by thomas-mc-work** [comment]
Ok, my fault. I forgot to move the data folders over :confounded:. Maybe you should a check with a nice message that the crucial data is missing.

**Comment by zaps166** [comment]
Hmm, from Readme:
```
The game will crash without original game data.
```
but the message about missing data is better than crash :smile: Maybe later :smile:


Yes, the precompiled binary is here: https://github.com/zaps166/NFSIISE/releases, I hope that it works properly...

**Comment by slrslr** [comment]
Got same error. Had to DL torrent magnet:?xt=urn:btih:7375613e21b6616d33286ddf6844fa273c85ddad which contained all data, move data folders (fedata, gamedata) from it and then run "convert_to_lowercase"
