### ISSUE TITLE
Does F10 for brightness control really work?

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#36]
I've pressed the key several times in the game but couldn't see any difference.

**Comment by zaps166** [comment]
The F10 key works for me, check also "brightness" settings from options/graphics.
Which OS do you use and which NFS build do you use? Is it OpenGL 2 version?

**Comment by thomas-mc-work** [comment]
The CLI says:

    Need For Speed II SE
      Wrapper v1.2.3
      Game    v1.1.2
      OpenGL  1

I'm on Ubuntu 14.04. `glxinfo` says among other things:

    # glxinfo  | grep ersion
    server glx version string: 1.4
    client glx version string: 1.4
    GLX version: 1.4
    OpenGL core profile version string: 4.3.13399 Core Profile Context 13.35.1005
    OpenGL core profile shading language version string: 4.40
    OpenGL version string: 4.5.13399 Compatibility Profile Context 13.35.1005

How can I use OpenGL 2? Does it make any difference?

**Comment by thomas-mc-work** [comment]
Ok, adding `gl2` to the compile script has enabled OpenGL 2 as described in the Readme. But much better: it fixed the problem! But what is different with OpenGL 2? Are there other advantages/disadvantages?

**Comment by zaps166** [comment]
OpenGL 2 uses GLSL, also for gamma (brightness in game), so it will always work. OpenGL 1 doesn't have this feature so changing brightness in game changes gamma using X11 on linux for entire screen - on some drivers it doesn't work. OpenGL 2 uses OpenGL ES 2 features so the game can be run on mobile phones, etc. If OpenGL 2 works properly - use it :)
