### ISSUE TITLE
Lots of build warnings

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#37]
When I compile the game then I receive a lot of warnings. Finally everything works fine, I'm just wondering if this is ok?

    Building OpenGL 2
    Building release for Linux (gcc)... FetchTrackRecords.c: In function ‘fetchTrackRecords’:
    FetchTrackRecords.c:82:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
        fgets(buffer, 80, f);
             ^
    FetchTrackRecords.c:83:10: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
        fscanf(f, "%d\n", (int32_t *)buffer);
              ^
    FetchTrackRecords.c:84:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
        fgets(buffer, 80, f);
             ^
    FetchTrackRecords.c:90:10: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(buffer, 80, f); //Skip unneeded line
              ^
    FetchTrackRecords.c: In function ‘readEntry’:
    FetchTrackRecords.c:60:7: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
      fgets(stfEntry->name, sizeof stfEntry->name, f);
           ^
    FetchTrackRecords.c:64:8: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
      fscanf(f, "%hi\n%d\n%d\n", &stfEntry->car, &stfEntry->time, &stfEntry->mode);
            ^
    In file included from Glide2x.c:30:0:
    Glide2x/OpenGL2.c: In function ‘loadShaders’:
    Glide2x/OpenGL2.c:262:2: warning: passing argument 3 of ‘glShaderSource’ discards ‘const’ qualifier from pointer target type [enabled by default]
      glShaderSource(g_vShader, 1, &vShaderSrc, &vShaderLen);
      ^
    Glide2x/OpenGL2.c:262:2: note: expected ‘const GLchar **’ but argument is of type ‘const GLchar * const*’
    Glide2x/OpenGL2.c:263:2: warning: passing argument 3 of ‘glShaderSource’ discards ‘const’ qualifier from pointer target type [enabled by default]
      glShaderSource(g_fShader, 1, &fShaderSrc, &fShaderLen);
      ^
    Glide2x/OpenGL2.c:263:2: note: expected ‘const GLchar **’ but argument is of type ‘const GLchar * const*’
    Kernel32.c: In function ‘MapViewOfFile_wrap’:
    Kernel32.c:501:7: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
       read(fMapping->fd, fileMap, size);
           ^
    OK!

**Comment by zaps166** [comment]
You can ignore these warnings. Getting the return value from `fscanf` and `fgets`, etc. is not needed in these places.

**Comment by zaps166** [comment]
Also you can check if you have less warnings after https://github.com/zaps166/NFSIISE/commit/83967f99fff95cccf680b473858668ba4625cf45 😄

**Comment by thomas-mc-work** [comment]
Alright, thanks. Yes, there are some less warnings.
