### ISSUE TITLE
Is there some chance to make a portable version for Software mode?

### ISSUE THREAD

**Issue by pasildan** [zaps166/NFSIISE#41]
Searching so much I couldn't find a single way to play in Software for Windows 10 64 bits. Is there some chance could be made a version for software mode? It's so cool looking some stages like Mediterraneo in sunset instead of daylight (3Dfx mode).
Basically the problem with software mode is when tried to apply different options/patches in like Win7 systems, the game gets frozen screen when starting any track (like proving grounds) but music, sound effects and announcer still being heard, but the game doesn't show any progress on screen (even though apparently the code still being running, so you can get out with keyboard).
 

Incredible job with the 3dfx portable edition by the way, quite nice job !

**Comment by zaps166** [comment]
Software mode is not supported - it is a separate executable in original game.

For playing the game in software mode on Windows it is possible to wrap DirectDraw DLLs and `eacsnd.dll` only to fix problems. But it is still a lot of work and I don't have time for it now.

**Comment by pasildan** [comment]
Unfortunate buddy, I really hope you can do it in the future. You made an incredible job with the portable edition for 3dfx. Unique I would say. This would be the ultimate edition for NFS II in modern systems adding the remaining software mode. I will be waiting for you if by any chance you can bring on the table a solution for software mode. Thanks for your effort and time good sir.

**Comment by pasildan** [comment]
I just managed to get a sort of workable Software mode for Windows 10, in theory should work for the original NFS II too. Main problem is I get the game working in like 15 frames per seconds. Really choppy, did you ever get a similar problem when coding the portable edition? can't realize how could fix that.

**Comment by zaps166** [comment]
Maybe you could run it using QEmu/DosBox/VirtualBox ?

**Comment by pasildan** [comment]
Yeah thanks my friend... I were testing with similiar softwares like that. By the way, about your previous research do you know if there is some way to set Software mode working without requiring the installation files into an optical drive (or virtual one)? I looked into install.WIN but that trick just works for some other 3dfx fixes around there. Would appreciate if you have some info. P.D: already copied the main folders from CD to my main nfs2 software mode folder.

**Comment by zaps166** [comment]
I'll send you patched executable to not require CD. It is easy to fix it in hex editor :)

**Comment by pasildan** [comment]
YahoOOOOOOOOOOOOOOOOOO!!!!!! after several tries and searching here and there, just made an executable and portable version for SOFTWARE MODE in windows 10 !!!! Of course this is not as  good as your 3dfx version since you made it available with many less files , but this is kind of the same for Software mode. There are currently 2 versions for NFS 2:  The original NFS II and NFSII SE with software mode. The only problem for the original game is that I cannot make it working with NO-CD, I would appreciate your fix. The SE game has the same no-cd problem but a second one which haven't realized how to fix just yet. The general sound appears to be apparently not synchronized completely well with the game, like 0.5 or 0.75 (maybe 1 second) delayed in comparison to your direct actions into the game (Talking about single player mode, where should be 0 delay after all). Do you know if there is some way to fix this sound delay issue? Would appreciate if you can let me know how to fix it. (P.D: I'm not talking about crackling sound, just about delay).

**Comment by zaps166** [comment]
@pasildan 
Could you send me an email?

**Comment by pasildan** [comment]
pasildany@hotmail.com     , Thanks good sir !

**Comment by pasildan** [comment]
hey buddy I'm the pasildan guy from your NFS II SE github page. Would
appreciate a lot the NO-cd files. Thank you a lot !!

2018-05-01 5:45 GMT-03:00 Błażej Szczygieł <notifications@github.com>:

**Comment by zaps166** [comment]
Done: https://github.com/zaps166/NFSIISEN
