### ISSUE TITLE
Map reset to game controller

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#43]
Would it be possible to allow mapping of the reset function [as it is with the `esc` button](#21)? Currently this can be triggered on a keyboard by the `F11` key.

**Comment by thomas-mc-work** [comment]
Would that be possible for the second reset button, too (`F12`)?

**Comment by zaps166** [comment]
> Very nice, thanks! Would that be possible for the second reset button, too (`F12`)?

Yes, but if you use second controller for first player, it will be swapped :smile:

**Comment by thomas-mc-work** [comment]
:smile: Could lead to funny situations. But still an advance for me.

**Comment by zaps166** [comment]
Done!

**Comment by thomas-mc-work** [comment]
Magnificient, thank you!
