### ISSUE TITLE
Slowdown every 2 second

### ISSUE THREAD

**Issue by TheAwesomeGem** [zaps166/NFSIISE#44]
I am experiencing slowdown every second on a race on Windows 10. Any possible solution?

**Comment by zaps166** [comment]
Hmm, I'll check this on Win10.

**Comment by zaps166** [comment]
The game is smooth on my Windows 10 (1709), Intel drivers.

**Comment by commanderconquer** [comment]
I got serious slowdown in splitscreen all the time in Win10. Single player works 100%. The computer stays highly responsive, so there is something with the game. Tested on 2 diff. screens (4K TV-60 Hz, G-Sync Monitor 165 Hz). Results are the same. Compatibility modes tested, too.

**Comment by zaps166** [comment]
So split screen slows down, but single player works properly? Which Windows version do you have? G-Sync means that you have NVIDIA GPU. Is it SLI?

**Comment by commanderconquer** [comment]
Thanks. Latest W10 1809 17763.437. Single RTX 2080 Ti. Single player great. We play with 2x xinput device.

**Comment by zaps166** [comment]
4k monitor, Windows 10 1709 16299.15, GTX 1080Ti, 2xDS3 controllers via ScpToolkit, default NFSIISE settings - no problems.
Additionally I have CPU power saving disabled in windows (set to 100%), no firewalls, no windows updates, no antivirus and nothing additional runs in background. Display scale set to 100%.

Please try without game controllers, try to change some settings in Windows / driver settings, disable background mess (telemetry, updaters, etc.). Maybe something is wrong with latest updates? Do you have another computer or another OS for testing?

---

IIRC I had a game slow down problem on W10 tablet a long time ago. After manual reinstalling Windows from USB stick, the game started working faster.

**Comment by commanderconquer** [comment]
Tried without my scptooled DS3's, torn off diagnostic etc. The game remain slow. The timer in the game is also slow (2 second 1 second approximately.) I will check it on win 7 computer later.

**Comment by commanderconquer** [comment]
Tested a laptop with core i3 + mx110 + win 10, performance was bad in singleplayer too.

Tested a desktop with core i3 + gtx 750 ti + win 7 performance excellent even with split screen.

I will install windows 7 again for this (and a few other) game as a second OS. I think new MS-"optimizations" flipped the table.

Other: I see the camera rotating crazy fast in the pause menu during race, as fast as a vga can displaying it. It should be moving more slowly. Isn't really a bug, just taking a note.

**Comment by zaps166** [comment]
> Other: I see the camera rotating crazy fast in the pause menu during race, as fast as a vga can displaying it. It should be moving more slowly. Isn't really a bug, just taking a note.

Try to set display to 60Hz and enable V-Sync. Be sure that game runs in exclusive full screen (on Windows 10 and OpenGL you shouldn't see e.g. the volume control OSD).

---

Today tested on the newest nvidia drivers and windows 10 1809 - split screen runs normally.

**Comment by commanderconquer** [comment]
I checked it with 60 fps + gsync. Now the game runs better but now I got a small hiccup every two seconds in split screen.

**Comment by commanderconquer** [comment]
I updated to the latest windows 10 (may update) 1903 18362.30 + nvidia 430.53 Hotfix. The problem vanished.

**Comment by zaps166** [comment]
So this was a driver/OS issue :)
Closing.
