### ISSUE TITLE
error: syntax error, unexpected NEW_IDENTIFIER  Error loading shaders, see console output! Terminado (killed)

### ISSUE THREAD

**Issue by Askmewho** [zaps166/NFSIISE#45]
I tried this game before on the pi3 and it works under mesa drivers. I have tried to run it again and I compiled against opengl, opengl es 2 and 1...none of these works. maybe its my driver. but for some reason it says than its an syntax error. maybe its something related to this code this time.

**Comment by zaps166** [comment]
I tried to run NFSIISE on RPi a long time ago (Arch Linux) using open source VC4 drivers and it worked properly on OpenGL, but IIRC not on GLES.

**Comment by Askmewho** [comment]
There are some changes on newers mesa than provide great features but breake some others... Maybe its just my setup. Great interpreter.

**Comment by Askmewho** [comment]
Could I provide any trace? What you suggest? Because full opengl could improve a lot the performance. Apitrace?
