### ISSUE TITLE
Cannot open shared library /usr/lib32/alsa-lib/libasound_module_pcm_pulse.so

### ISSUE THREAD

**Issue by josefnpat** [zaps166/NFSIISE#5]
Thanks for responding to tickets so quickly!

Now it looks like I may have an audio conflict - any ideas?

![image](https://cloud.githubusercontent.com/assets/646162/15749676/d3faa208-28a8-11e6-9cd2-6ebaa911decc.png)

I don't think it has to do with every file that I copied from my NFSIISE disc is in capitals ... but maybe?

**Comment by zaps166** [comment]
For ALSA probably you need `lib32-alsa-plugins` packet.

As described in README - the game crashes w/o game data (I'll fix it later, it should show a msgbox about missing data).

> I don't think it has to do with every file that I copied from my NFSIISE disc is in capitals ... but maybe?

The game **requires** small letters. Sorry, but this is Linux :smile:
Everything is in capital letters? I can also try to add capitals letters later...
You must mount a CD in small-letters mode (I have small letters on ISO image and CDEMU).

Maybe try this: http://superuser.com/questions/357253/linux-mount-iso-with-lowercase-directory-names

**Comment by josefnpat** [comment]
It seems I already have it installed (`steam` I guess?). I'm looking for a way to get the iso data in lowercase now!

```bash
seppi@seppi7:~♠ sudo pacman -S lib32-alsa-plugins
[sudo] password for seppi: 
warning: lib32-alsa-plugins-1.1.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) lib32-alsa-plugins-1.1.1-1

Total Installed Size:  0.18 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [----------------------] 100%
(1/1) checking package integrity                   [----------------------] 100%
(1/1) loading package files                        [----------------------] 100%
(1/1) checking for file conflicts                  [----------------------] 100%
(1/1) checking available disk space                [----------------------] 100%
:: Processing package changes...
(1/1) reinstalling lib32-alsa-plugins              [----------------------] 100%
```

**Comment by zaps166** [comment]
On your screenshot I can see that it can't load PulseAudio ALSA plugin. Do you use PulseAudio?

`ps -A | grep pulseaudio`

SDL2 supports PulseAudio directly, so it shouldn't need this plugin.

**Comment by josefnpat** [comment]
Ok, I think the pulseaudio thing is just a warning.

I used this script to rename all the data to lowercase and this resolved the actual issue I was having: http://www.linuxweblog.com/rename-files-folders-lowercase

moving to https://github.com/zaps166/NFSIISE/issues/6
