### ISSUE TITLE
Refactor build system

### ISSUE THREAD

**Issue by JayFoxRox** [zaps166/NFSIISE#51]
The build system (`compile_nfs`) is pretty bad; it takes a long time to compile the project.
The build system should support incremental builds and provide more feedback.

*(I'd suggest looking at CMake in case an exernal build system is considered)*

**Comment by zaps166** [comment]
It builds 1 sec on my CPU, so it's not slow. You can edit script if you don't want to build all components.
For C++ builds - modify script to not remove and build again C++ file if you do modifications in C code.
