### ISSUE TITLE
Game crashes on startup with "Application closed with a signal: 11"

### ISSUE THREAD

**Issue by radioactiveman** [zaps166/NFSIISE#52]
The game shows the intro videos and loading screen and then just crashes.
I'm using Arch Linux (x86_64) with the [nfs2se-git](https://aur.archlinux.org/packages/nfs2se-git)  AUR package.
After installing it I have copied the directory `fedata` and `gamedata` from the CD to `/opt/nfs2se/` as suggested. The file names were already lower-case, so this should not be an issue.

The console output is the following:
```
$ nfs2se 
Need For Speed II SE
  Wrapper v1.2.4
  Game    v1.1.2
  OpenGL  2
Application closed with a signal: 11
```
I tried also to use OpenGL 1 and disabling full screen mode. Both attempts did not help.

Output of glxinfo (truncated):
```
$ glxinfo -B
OpenGL renderer string: Radeon RX 560 Series (POLARIS11, DRM 3.27.0, 5.0.6-arch1-1-ARCH, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.1
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.1
```

If you need more information, please tell me.

**Comment by zaps166** [comment]
Maybe something is wrong with your game data? I can play the game on recent Manjaro updates on Radeon Vega 8.

**Comment by radioactiveman** [comment]
This was indeed the case. I got it working now with another ISO file. Back to the childhood... :smiley:
