### ISSUE TITLE
Application Closed with signal 11

### ISSUE THREAD

**Issue by electrodragon** [zaps166/NFSIISE#54]
I installed nsf2se aur pkg in my manjaro, then copied the FeData and GameData folders to /opt/nfs2se/
then renamed them all lowercase i.e. fedata, gamedata
then run the command
$ nfs2se
and it showed that application closed with signal 11 error.
Any Fix?

**Comment by zaps166** [comment]
Runs on my Manjaro.

---

Do you have 32-bit GPU drivers installed?

> then renamed them all lowercase i.e. fedata, gamedata

Only these dirs or all files? All files need to be lowercase.

Is it NFS2SE or NFS2 game data?

Do you have permissions for reading for all fedata and gamedata dirs and files?

**Comment by electrodragon** [comment]
Nvidia Proprietary drivers are installed, don't know much about 32-bit gpu

I just copied and pasted those folders to /opt/nfs2se/, didn't renamed sub files/dirs or other dirs/files.

Its Need-for-Speed-II-SE_Win_EN_RIP-Version.zip

Yes all permissions were given with 
`sudo chmod -r 777 /opt/nfs2se/fedata /opt/nfs2se/gamedata`

**Comment by zaps166** [comment]
> Nvidia Proprietary drivers are installed, don't know much about 32-bit gpu

example: `lib32-nvidia-440xx-utils` - 32bit driver (440xx series)

> didn't renamed sub files/dirs or other dirs/files.

Use [convert_to_lowercase](https://github.com/zaps166/NFSIISE/blob/master/Need%20For%20Speed%20II%20SE/convert_to_lowercase) script from this repo to be sure. All subdirs and all files must have small letters.

**Comment by zaps166** [comment]
Please check again with #57 fix
