### ISSUE TITLE
Problems to use my Logitech G29 Wheel in Linux

### ISSUE THREAD

**Issue by leillo1975** [zaps166/NFSIISE#56]
Hello
When I try to play with my G29 Wheel on Ubuntu, I get the following error:
https://youtu.be/RIs_nudYhik

Is impossible to select one option in the menu because is like you are pressing constantly the down button.

**Comment by zaps166** [comment]
Hi!

Configuration of this is not easy :D Probably you need to do something with axes.

Edit `~/.nfs2se/nfs2se.conf` and try to do something with (uncomment and edit):
`Joystick0AxisValueShift`
`Joystick0Axes`
`Joystick0Buttons`
Especially `Joystick0Axes` after color (negative values, etc.). There should be a simple guideline at the top of the file.

You can use any software for watching your wheel (evdev), maybe try `evdev-joystick`.

**Comment by leillo1975** [comment]
If I push and mantein the clutch (Axis1) to the medium value, is possible to stop this error...

**Comment by leillo1975** [comment]
I remove clutch changing Joystick0Axes=0,2,3:1,0,0 
Where Axis0 is direction, Axis2 is Accelerator and Axis3 is brake.... but now I need to push the accelerator some to use the menu as normal.

**Comment by leillo1975** [comment]
Today it don't work again.... something is not good here

**Comment by mattissf** [comment]
Hi @leillo1975 - I had the same problems with my G25. I had to change the axis settings to this:

Joystick0Axes=0,1,2,3:0,-1,1,1

It was just dumb luck after a lot of trial and error. But it works!

**Comment by leillo1975** [comment]
I will try it tomorrow. Thanks a lot!

**Comment by leillo1975** [comment]
Finally I could try it today, and it works, but I can't accelerate more than 49kmh, and the accelerate bar stops on the half

**Comment by zaps166** [comment]
@leillo1975 Try to set one of values: `0`, `1`, `-1` after colon (`:`) for axis which doesn't work properly and check every settings (save the file and restart game).
First value after colon corresponds to first chosen axis, etc:
`Joystick0Axes=0,1,2,3:0,-1,1,1` - `0` type for axis `0`, `-1` type for axis `1`, `1` type for axis `2` and `3`.

**Comment by zaps166** [comment]
3 different solutions:

Config file:
- edit `~/.nfs2se/nfs2se.conf`
- remove `#` from beginning of line and set to: `Joystick0Axes2=0,1,2,3,4,5:0,-1,0,0,0,0`

Vanilla kernel driver (not touching config file):
 - install `oversteer` application (AUR)
 - choose "Driving Force GT" or "Driving Force Pro" compatibility
 - press apply
 - check the "Accelerator + Brakes" combine button

`new-lg4ff-dkms-git` kernel driver (AUR, not touching config file):
- install `oversteer` application (AUR)
- check the "Accelerator + Clutch" combine button.

**Comment by zaps166** [comment]
Now you can also set `JoystickDisableAxesInMenu=1` in config file.
