### ISSUE TITLE
Compiling on Mac

### ISSUE THREAD

**Issue by Chuchein** [zaps166/NFSIISE#58]
A long time a go a was able to run this (thoug it wasnt exactly from this site) but I cant make it work now
The Lower upper case didnt work, but I found another way... but it still dont work
Ill tell you what I did, a aint no computer genious.
I downloaded NFSIISE-master 2
Then i got a cd image and copy FEDATA and GAME DATA in NFSIISE-master/Need For Speed II SE 
Made everything lower case,
then opened on a terminal the compile_nfs and this is what I get 

Last login: Thu Jul  9 14:52:14 on ttys000
MYNAME-MacBook-Pro:~ MYUSER$ /Users/MYFOLDER/Documents/Juegos/NFSIISE-master\ 2/compile_nfs ; exit;
/Users/MYFOLDER/Documents/Juegos/NFSIISE-master 2/compile_nfs: line 133: cd: src: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proceso completado]

So... what am I doing wrong?

THanks! sorry

**Comment by zaps166** [comment]
Sorry, I forgot to response.

Clone git repository and init and update submodules, **don't download the source**, because it is incomplete. Also install SDL2 library (maybe use [brew](https://brew.sh/)).

Btw. can macOS Catalina/Big Sur still run 32-bit binaries?
