### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by endkunde** [zaps166/NFSIISE#59]
Dear Developers of NFSIISE.

Is it possible to get a Windows 10 based list or in best cases a tutorial of needed software and configuration steps as well as build workflow to your project in order to take part and provide more features or bugfixes?

Cheers.
Christian

**Comment by endkunde** [comment]
A screen capture video would just help. Thanks in advance.

**Comment by zaps166** [comment]
I always cross compile from Linux. Use Arch Linux or Manjaro Linux and `mingw-w64-sdl2` package with `mingw-w64-gcc` compiler.
