### ISSUE TITLE
movie file missing

### ISSUE THREAD

**Issue by josefnpat** [zaps166/NFSIISE#6]
So I've renamed all my files to lowercase using this script:

http://www.linuxweblog.com/rename-files-folders-lowercase

Here's my `find .` output: http://codepad.org/zdwP0sWr

When I run the binary, it can't seem to find the `MOVIE FILE`. Any idea if I'm missing the one I need?

![image](https://cloud.githubusercontent.com/assets/646162/15750254/64ec5a84-28ab-11e6-8784-7256757c4630.png)

**Comment by zaps166** [comment]
Maybe still something wrong with files:
```bash
find fedata/ gamedata/
```
[fedata_and_gamedata.txt](https://github.com/zaps166/NFSIISE/files/295935/fedata_and_gamedata.txt)

This is my result. Do you have missing files or capital letters somewhere?

**Comment by zaps166** [comment]
I can see many differences, hmm...

**Comment by josefnpat** [comment]
I did a sort and ran meld:

![image](https://cloud.githubusercontent.com/assets/646162/15750732/297b7532-28ad-11e6-9353-ccce892e8e3f.png)

I just rechecked, and I think I pulled out my NFSII iso, not my NFSIISE iso. Let me fix that ...

**Comment by zaps166** [comment]
This is port of NFSIISE, so I think that data from NFSII won't work properly :)

**Comment by josefnpat** [comment]
Wow, what a blast from the past! This is amazing work! Now to find someone to play TCP :)

![2016-06-02-10 51 13-screenshot](https://cloud.githubusercontent.com/assets/646162/15751599/48e48cf8-28b0-11e6-894e-5ddf957caf41.png)

**Comment by josefnpat** [comment]
Yeah, this is invalid - I was using NFSII, not NFSIISE.

**Comment by zaps166** [comment]
Btw. I can't start the game today :smile: Something is wrong...
