### ISSUE TITLE
I'm getting major slowdowns on the windows stable release

### ISSUE THREAD

**Issue by Ninkyo** [zaps166/NFSIISE#60]
I'm getting major slowdowns on the windows stable release and not sure what could be causing it, I've messed around with v-sync and cores in the config and even tried compatibility mode but no luck, thanks.

**Comment by endkunde** [comment]
Hi @Ninkyo .

The following configuration runs stable for me:

UseOnlyOneCPU=1
StartInFullScreen=0
VSync=1
MSAA=16
UseWindowSizeForFullScreen=1
WindowSize=1600x1200
KeepAspectRatio=1
#Joystick0AxisValueShift=8448
#Joystick1AxisValueShift=8448
#Joystick0Axes=0,12,13,14:0,1,1,1
#Joystick1Axes=0,12,13,14:0,1,1,1
#Joystick0Buttons=0,15,16,3,4,5,6,7,-1,-1,-1,11,12,13,14
#Joystick1Buttons=0,15,16,3,4,5,6,7,-1,-1,-1,11,12,13,14
#Joystick0EscButton=-1
#UseSpringForceFeedbackEffect=0
#WindowsForceFeedbackDevice=-1
#LinearSoundInterpolation=1
#UseGlBleginGlEnd=0
#Port1=1030
#Port2=1029
#Bcast=255.255.255.255
LinuxCOM1=/dev/ttyS0
LinuxCOM2=/dev/ttyS1
LinuxCOM3=/dev/ttyUSB0
LinuxCOM4=/dev/ttyUSB1

My system:
AMD 3800X
Nvidia RTX 2080
64 GB DDR4 3600 RAM

**Comment by endkunde** [comment]
Does it work now?

**Comment by zaps166** [comment]
Does it work? It should run properly without changing anything in config file. I use Linux most of time, so I'm not testing it under Windows especially after every buggy Windows 10 update...

**Comment by dee-dubya** [comment]
I tried using @endkunde config, but I'm having major slowdown issues as well. Races start out pretty stable, but then start dropping more and more frames as the race goes on to the point that it becomes nearly unplayable.

**Comment by zaps166** [comment]
Nothing need to be changed in the config file to get it work properly. What operating system do you have? I never had this issue on Linux. How long do I have to play to reproduce the issue?

**Comment by gameboybenutzer** [comment]
I also have slow down issues on Windows. Can we provide any debugging information to find the culprit?

**Comment by zaps166** [comment]
I don't have any issues on WIndows 10 + GTX 1080Ti. I played ~15min on default settings.

---

Give me configuration do you have:
- Windows 10 version
- do you have antivirus?
- are Windows background services enabled or disabled (telemetry, updates, defrag, optimizers, MS antivirus, etc.)?
- GPU model
- GPU driver version
- is FreeSync/G-Sync enabled or disabled (it is better to disable it for this game)?
- is triple-buffering enabled or disabled for OpenGL?
- do you use default configuration in GPU driver control panel?
- is default NFSIISE config used?
- do you play on fullscreen?
- do you run `nfs2se.exe` or `nfs2se-gl1.exe` (`nfs2se-gl1.exe` shouldn't be used, it is designed for ~15yo machines)?
- do you use any apps like frame limiters (e.g. nvidia control panel or RTSS) for this game?
- do you have v-sync enabled?

My config (qemu Q35, EFI, i7-8700k (6T 12C), HPET enabled, 3840x2160, scale 150%):
- Windows 10 1809, not updated
- no
- disabled everything I could,
- GTX 1080Ti
- 461.72 DCH
- tried both enabled and disabled (FreeSync as G-Sync compatible)
- tried both enabled and disabled (when triple-buffering is enabled, the game flickers e.g. on loading screen)
- tried both - default and customized (for triple-buffering)
- yes, I use default NFSIISE config file
- yes
- `nfs2se.exe`
- tried both: with 60 FPS cap and unlimited
- yes

---

Tip: you can cap frame rate to your screen refresh rate (usually 60 FPS) to get rid of v-sync/triple-buffer lag e.g. in nvidia control panel or using RTSS.

Maybe something is wrong with newer windows versions?

---

You can also check your timer precision (link to `winmm` library):

```c++
#include <windows.h>

static double gettime()
{
    LARGE_INTEGER Frequency, Counter;
    QueryPerformanceFrequency(&Frequency);
    QueryPerformanceCounter(&Counter);
    return (double)Counter.QuadPart / (double)Frequency.QuadPart;
}

#include <iostream>

using namespace std;

int main()
{
    constexpr int n = 100;

    timeBeginPeriod(1);

    auto t1 = gettime();
    for (int i = 0; i < n; ++i)
        Sleep(1);
    auto t2 = gettime();

    cerr << (t2 - t1) * 1000.0 / n << " ms" << endl;

    timeEndPeriod(1);
    return 0;
}
```

I use HPET on qemu/kvm, my result is ~1.85.

**Comment by gameboybenutzer** [comment]
Give me configuration do you have:

    - Windows 7x64 and 10x64
    - No Antivirus except Windows Defender Crap
    - Everything disabled, as far as possible
    - Ryzen7 8C/16T and i7-10700 8C/16T
    - nVidia GTX960 and RTX2070super on latest driver
    - no gaming monitor
    - disabled triple buffering
    - default GPU configuration
    - default NFSIISE configuration
    -fullscreen and windowed
    - tried all the executables
    - no frame limiters
    - vsync enabled and disabled

**Comment by madseason666** [comment]
I'm having the exact same issue on Windows 11.

**Comment by zaps166** [comment]
Reproduced on Windows 10 laptop. Sometimes it's smooth, sometimes it slowdowns very often... It really depends on some weird thing like Windows 10 update, drivers, hardware. On my 2nd laptop with old (not updated Windows 10) with Ryzen 2500U the game runs smooth.

**Comment by madseason666** [comment]
Has to be something from the newer builds of Windows 10/11.
It works fine in 1809, for instance.

**Comment by zaps166** [comment]
> It works fine in 1809, for instance.

It's my Windows on VM, so that's why it's working :smile: On Laptop when I reproduced I have 20H2.

**Comment by madseason666** [comment]
> > It works fine in 1809, for instance.
> 
> It's my Windows on VM, so that's why it's working 😄 On Laptop when I reproduced I have 20H2.

Wish I could be of more help, but I have no clue what was changed on Windows, I'm just an end-user 😭

**Comment by zaps166** [comment]
I recompiled with newest SDL 2.0.20 and new GCC/MinGW - the same problem. Weird thing is it doesn't happen on all PCs with new Window.

**Comment by madseason666** [comment]
I found a workaround of sorts.
There's this option called "Disable Fullscreen Optimizations" under the Compatibility Tab.
I recalled having similar issues with the DOSbox ECE and enabling this flag solved it.
As I said I don't know much about programming, do DOSbox ECE and this implementation of NFS2SE use similar libraries?

In any case, I played some races and it works as intended... maybe that was it, or maybe yesterdays W11 update.

I can do more testing but it's getting late 😴

**Comment by zaps166** [comment]
The workaround for slowdowns on Windows might be uncomment (remove `#`) and set `UseOnlyOneCPU` to `0` in config file. But it disables a workaround for another problem - the game might freeze or not start at all (it depends).

- If the game somehow starts with `UseOnlyOneCPU=0` let me know about game speed.
- If the game can't start with `UseOnlyOneCPU=0`, keep the default value (`1`) and change CPU Affinity for `nfs2se.exe` at runtime (you can use [Process Explorer](https://download.sysinternals.com/files/ProcessExplorer.zip)).

**Comment by madseason666** [comment]
On my System (Win11, 4790k, gtx1080, 16gb, ssd).

`UseOnlyOneCPU=0` Black Screen/freeze after intro

CPU affinity is by default on 0, so I guess there's nothing to change there.

**Comment by zaps166** [comment]
> CPU affinity is 0 by default on runtime, so I guess there's nothing to change there, unless I'm doing something wrong?

When you start a race, select all CPUs and press OK.

**Comment by madseason666** [comment]
> > CPU affinity is 0 by default on runtime, so I guess there's nothing to change there, unless I'm doing something wrong?
> 
> When you start a race, select all CPUs and press OK.

Ah, that worked during the race, and it froze after going back to main menu.

**Comment by zaps166** [comment]
> Ah, that worked during the race, and it froze after going back to main menu.

Is game speed ok with this?

**Comment by madseason666** [comment]
> > Ah, that worked during the race, and it froze after going back to main menu.
> 
> Is game speed ok with this?

Game speed seems stable, or is your question related to if it runs a little too fast, or feels 'off'? If that's the case, I can't tell.

**Comment by zaps166** [comment]
Similar issue about game speed is #80. Maybe it's one and the same issue.

**Comment by madseason666** [comment]
Could be, though in my particular case it didn't speed up, just slow down (without the affinity changed).

**Comment by zaps166** [comment]
Game with fix I've provided works on Windows 10 on one of my computers.

**Comment by mashakos** [comment]
I can test on my end if a binary with the fix is available

**Comment by zaps166** [comment]
New binary is available!

**Comment by mashakos** [comment]
The new version clears the timing issues which is fantastic. One snag: my gamepad config (which I based off of a user ticket) doesnt work anymore

Joystick0Axes=0,1,5,2:0,0,0,0
Joystick0Buttons=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14

**Comment by madseason666** [comment]
New version works great on W11 👍

**Comment by zaps166** [comment]
@mashakos Is the gamepad working with different key mapping or it is not detected at all?

**Comment by mashakos** [comment]
not detected at all. Was the syntax format of the .conf file updated perhaps? I didn't delete my existing one
