### ISSUE TITLE
Configuration File Doesn't Work on Windows

### ISSUE THREAD

**Issue by Wyatt100** [zaps166/NFSIISE#61]
Hi,

Changing the configuration through the .bat doesn't elicit any changes in the game. It just loads into full-screen 4:3 with no MSAA. I have it installed in my root C: drive.

**Comment by endkunde** [comment]
If the bat opens the file then the path should be correct. Maybe you try to open and change the file with admin rights? see if it helps.

**Comment by Wyatt100** [comment]
Still no changes.

**Comment by endkunde** [comment]
From line 362 in [Wrapper.c](https://github.com/zaps166/NFSIISE/blob/master/src/Wrapper.c) you can see that the config file is read from the home dir and as you can open it via batch file it should be located correctly. In case you do not have a write lock on that file i am out of ideas for a solution to your issue. Sorry.

**Comment by endkunde** [comment]
I am not sure if this is the reason, but please also check that ominous empty line at the end of the file as stated in the file:

`#This is the "Need For Speed II SE" wrapper configuration file.
#Don't modify the "nfs2se.conf.template" file, be sure that you are editing configuration inside home directory (created during the first run):
#	Linux:   "~/.nfs2se/nfs2se.conf",
#	Windows: "%AppData%\.nfs2se\nfs2se.conf".
#Leave empty line at the end of the file!`

**Comment by superblobster** [comment]
I encountered the same issue and figured it out.

You are supposed to manually remove the hashtags in front of the list of settings at the end of the file. The hashtags mean the line is treated as a comment and ignored by the wrapper in favor of internal default settings until the hashtags are removed.

Whoever did this was thinking like a programmer and not like a normal rational user! This is such hostile design.

Oh well, at least the wrapper works perfectly. It's better than the other NFS2 patches out there.

**Comment by zaps166** [comment]
Hi

1. `#` must be removed from the begining of the line. It should be documented at the beggining of the file - sorry for that.
2. @superblobster Normal user needs GUI for settings which I never written for this game port... :smile:

**Comment by endkunde** [comment]
@zaps166 : Here i would like to wave my hands in direction of https://github.com/zaps166/NFSIISE/issues/59 because i would like to contribute some spare time to this project.
