### ISSUE TITLE
Please use the v1.1 exe of the game in stead of v1.0

### ISSUE THREAD

**Issue by hinsert** [zaps166/NFSIISE#63]
V1.1 of the game implemented TCP/IP support for online play. It was an official release by EA but quite difficult to find.

Is it possible to use this version so that players can enjoy playing online or via LAN?

[nfs2se_networkfix.zip](https://github.com/zaps166/NFSIISE/files/5745188/nfs2se_networkfix.zip)

Updates
-------
- Addition: TCP network protocol.
- Addition: Ability to play network games with a "peer to peer" packet transfer model.
- Fix:      Force Feedback chugging.
- Fix:      Videos by-passed when a fluttering or uncalibrated joystick was plugged in.

Files Changed
-------------
The following files have been patched:
	nfs2sea.exe
	nfs2sen.exe
	text.*
If you do not have the updated text.* files in the same directory
as the .exe file, the game will not run.

**Comment by zaps166** [comment]
It is already TCP/IP version.

**Comment by hinsert** [comment]
You're right, I didn't check it well enough. Apologies!
