### ISSUE TITLE
Minimizing/maximizing game influences sound playback speed

### ISSUE THREAD

**Issue by radioactiveman** [zaps166/NFSIISE#65]
### Description ###
When minimizing the game with ALT+TAB it may happen that the sound is played twice or four times as fast after the game has been maximized again. Repeating this increases the speed even more. Happens in the menu and also races.

### Environment ###
- Arch Linux
- nfs2se-git
- SDL2 2.0.14
- PulseAudio 14.1

**Comment by zaps166** [comment]
When the game is minimized, the sound is stopped. What WM/DE do you have?

**Comment by radioactiveman** [comment]
> When the game is minimized, the sound is stopped.

Yes, that's usually the case, but not always. And if the sound does not stop, this issue occurs.
The game is then shown multiple times in the PulseAudio volume control.

Please see the attached screencast. This is a very weird issue. :smile:

> What WM/DE do you have?

I don't think this is related, but it's Xfce 4.16.

https://user-images.githubusercontent.com/1301412/104954616-d95cc900-59c8-11eb-84c9-9b886aff640c.mp4

**Comment by zaps166** [comment]
Sorry, I forgot to response. IIRC I tried many times, but was able to reproduce it only once.

- Does it happen also on PipeWire (as PulseAudio replacement)?
- Can you try on OpenBox WM (`openbox --replace`)?

**Comment by HadetTheUndying** [comment]
> Sorry, I forgot to response. IIRC I tried many times, but was able to reproduce it only once.
> 
>     * Does it happen also on PipeWire (as PulseAudio replacement)?
> 
>     * Can you try on OpenBox WM (`openbox --replace`)?

Can Confirm that it happens on Pipewire's Pulse Implementation too.

```
 hadet@endurance  ~  pactl info 
Server String: /run/user/1000/pulse/native
Library Protocol Version: 34
Server Protocol Version: 35
Is Local: yes
Client Index: 97
Tile Size: 65472
User Name: hadet
Host Name: endurance
Server Name: PulseAudio (on PipeWire 0.3.28)
Server Version: 14.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-Grace_Design_SDAC-00.analog-stereo
Default Source: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-mono
Cookie: 11c5:6843
```
