### ISSUE TITLE
Cant get it to compile for Windows

### ISSUE THREAD

**Issue by Juli199696** [zaps166/NFSIISE#66]
I always get missing SDL2 include errors. I followed the Tutorial but i cant get it to work. Tried to include SDL2 libs.

Is this project going on?

**Comment by zaps166** [comment]
I cross-compiled this for Windows using mingw-w64 on Arch Linux. Compilation on Windows also should be possible, but `compile_nfs` is designed for Linux host. Try to look at `if [[ $BUILD_WINDOWS == "yes" ]]; then` and write similar commands, but on Windows terminal. Use mingw-w64 compiler (not Visual Studio) and use SDL2 library.

**Comment by Juli199696** [comment]
i used Debian and Ubuntu for it but it wont work. What SDL2 Files i need to install?

**Comment by zaps166** [comment]
> What SDL2 Files i need to install?

SDL2 for Windows (mingw), `include/SDL2` and `libSDL2.dll.a`.

On Arch Linux it is `mingw-w64-sdl2` from AUR.

**Comment by zaps166** [comment]
Did you manage to compile?
