### ISSUE TITLE
Process doesn't end after exit

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#67]
When I want to exit the game, then process prints an error and stays alive, until I kill it:

    malloc_consolidate(): invalid chunk size

But this doesn't always happen. I could figure out how it's been triggered.

I'm not sure since when this happens. The game has been compiled on Ubuntu 20.04 with the `gl2` switch.

**Comment by aznlir88** [comment]
Yep I get the same but no other problems

**Comment by zaps166** [comment]
I hope it's now fixed!
