### ISSUE TITLE
The `pioneer` cheat doesn't seem to work

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#69]
Typing `pioneer` in the main menu is being recognized and confirmed as expected in the first place. But in the race the top speed is the same as without the cheat.

**Comment by zaps166** [comment]
Works for me, just tested :smile:

**Comment by zaps166** [comment]
`pioneer` never changed top speed, only acceleration.

**Comment by zaps166** [comment]
As I remember correctly, Style can change top speed: Wild, Arcade, Simulation, etc.

**Comment by thomas-mc-work** [comment]
> pioneer never changed top speed, only acceleration.

That'd explain it. Thank you!
