### ISSUE TITLE
Menu objects not loading unless there's active input

### ISSUE THREAD

**Issue by phraggers** [zaps166/NFSIISE#71]
Running Arch x64 and i3wm (I have a feeling i3wm is to blame here). Builds fine, game runs like a dream, haven't noticed any other issues so far (Only played 1 race so far) but the game seems to stop when in menu (main menu, post race screens etc) until there's input, so to keep the game running I need to wiggle the mouse constantly whenever I'm expecting a menu to update, otherwise I'm just staring at the blank background image when the buttons animate and slide off-screen!

Hope my descriptions made sense, it's a bit weird to explain. Here's a video demonstration: https://youtu.be/Jv3-gm5HcI0

edit: Oh should probably say in case it's necessary: Built using "yay -S nfs2se-git" which deals with all the pre-reqs, build config etc for me (I'm very lazy)

**Comment by zaps166** [comment]
Hi! Try this: https://github.com/zaps166/NFSIISE/releases/download/v1.2.4/nfs2se-linux.tar.gz
Something has changed recently... Maybe SDL2 issue?

**Comment by phraggers** [comment]
Yep that build works perfectly. Never seen a bug like that before, very weird! I didn't show it in the video but if I don't move the mouse even the music stops, like the whole game loop stops and doesn't even fill the audio buffer.

**Comment by zaps166** [comment]
I have the same when using AUR package. It worked properly, now doesn't work - probably due to SDL2 updates...

**Comment by zaps166** [comment]
I checked it now, it happens on fullscreen + SDL 2.0.16 only. SDL2 main branch and SDL2 2.0.14 are working properly.

**Comment by zaps166** [comment]
SDL 2.0.18 is already released, but Arch Linux still has old version of 32-bit SDL2. Here is modified PKGBUILD: [lib32-sdl2.zip](https://github.com/zaps166/NFSIISE/files/7662440/lib32-sdl2.zip)
