### ISSUE TITLE
Skybox is broken on OpenGL 2

### ISSUE THREAD

**Issue by De-M-oN** [zaps166/NFSIISE#72]
Hello
With the OpenGL 2 exe the Skybox is broken:

https://abload.de/img/nfs2se_2021_11_05_16_dvkj8.png

OpenGL 1 file and also regular sea file it looks how its supposed to look:
https://abload.de/img/nfs2sea_2021_11_05_16mhj2c.png

I'm using a Windows 10 Computer
with Intel i9 9900k and RTX 2080 Ti.
My Display Resolution is 2560x1600 (16:10)

**Comment by zaps166** [comment]
#68

**Comment by zaps166** [comment]
If you disable gamma (set "Brightness" to "1" in game settings), the horizon will be correct.

**Comment by zaps166** [comment]
Fixed!
