### ISSUE TITLE
Statically linked binary - Linux

### ISSUE THREAD

**Issue by charsi** [zaps166/NFSIISE#73]
Thanks for sharing this! One of my favourite games that brings back good memories. 

The game builds and runs fine but when i coped the files to a another computer I got -
`./nfs2se: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
`
I had to do `sudo apt install libsdl2-dev:i386` on the new computer to fix this. 

Is it possible to not have to install libsdl to run the game?  
I tried adding `-statc` to the gcc command (in compile_nfs)-
`$CC -static -no-pie -nostartfiles $C_FLAGS -DNEED_DSO_HANDLE -DSTACK_REALIGN $OPENGL_DEFINE -o "../Need For Speed II SE/nfs2se" NFS2SE.Elf32.o *.c -lSDL2 $OPENGL_LIBS $STRIP -Wl,-rpath=\$ORIGIN -Wl,-estart`

But this creates this error when compiling - 

```
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: /tmp/cctQ9O94.o: in function `gethostbyname_wrap':
Wsock32.c:(.text+0xe4): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
```

I searched online and [found](https://stackoverflow.com/a/21858004/3761234) I'll have to recompile glibc with `--enable-static-nss` flag. Any easier way around having to use gethostbyname?

**Comment by zaps166** [comment]
Go to [Releases](https://github.com/zaps166/NFSIISE/releases) and download the release for Linux. It is linked to the old and stable SDL2 library.

**Comment by zaps166** [comment]
You shouldn't use `-static` flag, because it will also link statically to glibc. Use static SDL2 library file (add full path to `libSDL2.a` static file instead of `-lSDL2` and add it's dependencies (if any)).
