### ISSUE TITLE
Pls tell me how to compile this on linux arm32

### ISSUE THREAD

**Issue by Painadath** [zaps166/NFSIISE#75]

**Comment by zaps166** [comment]
What Linux distribution and device do you have? You need 32-bit GCC compiler and 32-bit SDL2 library.
If you have armv7 (32-bit) Arch Linux, try to install AUR `nfs2se-git` package.

**Comment by Painadath** [comment]
Raspbian bullseye on raspberry Pi 3

**Comment by zaps166** [comment]
Install `libsdl2-dev` package, git and gcc compiler
Clone repository `git clone https://github.com/zaps166/NFSIISE.git`
Go to cloned directory: `cd NFSIISE`
Download submodules: `git submodule update --init`
Compile: `./compile_nfs cpp`

Now wait afew minutes.
