### ISSUE TITLE
uncontrollable key clicks

### ISSUE THREAD

**Issue by cziss** [zaps166/NFSIISE#77]
Hi, I have strange problem. In main menu or every submenus it's like I clicking UP button. It's impossible to use game then.

**Comment by zaps166** [comment]
Do you have gamepad connected? Or does your SDL2 library detects other system inputs as a gamepad?
What's you OS? Did you compile from soures?

**Comment by cziss** [comment]
Problem appears the same with connected or not connected gamepad. Sorry, I don't know how I check if my SDL2 library detects something else. I use Manjaro Linux. It's compiled from aur.

**Comment by zaps166** [comment]
I don't have any problems on Manjaro Linux. Probably some of your sensors or other devices can be detected as gamepad.

Try this:
- edit `$HOME/.nfs2se/nfs2se.conf`
- set this:
```
Joystick0Axes=-1,-1,-1,-1:0,0,0,0
Joystick1Axes=-1,-1,-1,-1:0,0,0,0
Joystick0Buttons=-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
Joystick1Buttons=-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
```

**Comment by cziss** [comment]
Hi, I figured out that this settings works for me.

`Joystick1Axes=0,1,2,3:0,0,0,0
Joystick0Axes=-1,-1,-1,-1:0,0,0,0
Joystick2Axes=-1,-1,-1,-1:0,0,0,0
Joystick1Buttons=0,1,2,3,4,5,6,7,8,9,10,11,12
Joystick0Buttons=-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
Joystick2Buttons=-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1`

But force feedback on gamepad not working and also when I'm in race and click "esc" "enter" stops working and I can"t leave, restart ... game.

Funny is, that all that works fine some time ago, even force feedback.

**Comment by zaps166** [comment]
Force feedback might not work if you use second gamepad. Maybe workaround or SDL2 update is needed to skip some devices.
