### ISSUE TITLE
Black Screen after clicking on "Race"

### ISSUE THREAD

**Issue by Luciogi** [zaps166/NFSIISE#79]
Master Branch has some bug which causing following issues
- Game Scene video do not play (Expected: Scene video should play)
- Black Screen and Freezes after click on "Race"

Note: 3rd Release does not have above problems

Tested on Fedora 35

**Comment by zaps166** [comment]
Works properly for me.

Missing information - operating system (if Linux - distribution, is it from AUR?), GPU drivers...

**Comment by zaps166** [comment]
ok, closing!
