### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ckorn** [zaps166/NFSIISE#8]
What license is the code under?

**Comment by zaps166** [comment]
Good question... :smiley:
Is it necessary (e.g. for Linux package)?

**Comment by ckorn** [comment]
Yeah, I would like to create a Debian package for my Ubuntu gaming site playdeb.net.

It would be good that it has a license.

**Comment by zaps166** [comment]
I'm not a lawyer, but I can add a license for this including asm code.

**Comment by zaps166** [comment]
GPLv3

> Yeah, I would like to create a Debian package (...)

Also check for updates, have fun!
