### ISSUE TITLE
Game speed fluctuates on Windows

### ISSUE THREAD

**Issue by mashakos** [zaps166/NFSIISE#80]
The game jumps from normal speed to 4x fast forward for a split second at random points during a race.

On Win10 x64, 9900k, nvidia card

**Comment by zaps166** [comment]
Similar to #60 ?

**Comment by mashakos** [comment]
its not a slowdown on my end, more like: game speed jumps from 1x to 1000x for 1-2 secs then goes back to normal speed.

**Comment by zaps166** [comment]
Ok, for me it's the same bug (timers problem). Let's continue it in #60 .
