### ISSUE TITLE
When compiling, get an error: DInput.c:126:68: error: ‘SDL_HAPTIC_STEERING_AXIS’ undeclared 

### ISSUE THREAD

**Issue by TimRadon** [zaps166/NFSIISE#85]
Good day,
when I compile, I get an error: 

constantine@constantine-MS-7596:~/games/nfs2/NFSIISE$ ./compile_nfs
Building OpenGL 1
Building release for Linux (gcc)... DInput.c: In function ‘setEffect’:
DInput.c:126:68: error: ‘SDL_HAPTIC_STEERING_AXIS’ undeclared (first use in this function); did you mean ‘SDL_HAPTIC_SPHERICAL’?
  126 | nstant->direction.type = useHapticPolar ? SDL_HAPTIC_POLAR : SDL_HAPTIC_STEERING_AXIS; //di_eff->flags shows that POLAR is used (0x20)
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              SDL_HAPTIC_SPHERICAL
...

Maybe somebody could help ?
Thank you

**Comment by zaps166** [comment]
Fixed!

**Comment by TimRadon** [comment]
Thank you !
