### ISSUE TITLE
Occasional crashes when playing online with unlocked version with cheats

### ISSUE THREAD

**Issue by aznlir88** [zaps166/NFSIISE#87]
As I play online from time to time i noticed that if someone host server on unlocked version of the game and add cheats for funny stuff wrapper version sometime cannot handle something and crash.

Is there any way to improve the compatibility with unlocked hosts and cheats added?

If there is a way to provide logs when it happens I would love to do so. Only need some tips on how to get these logs.

**Comment by zaps166** [comment]
Try to compile with debug info and run via `gdb`.

**Comment by aznlir88** [comment]
How to compile with debug info? I see no info in README file. Would it be something like:

`./compile_nfs cpp debug`

?

**Comment by zaps166** [comment]
`./compile_nfs debug`, but install `yasm` first.

---

Alternatively you can use `cpp` flag, but it will build much slower. It's designed mainly for non-x86 CPUs.

**Comment by aznlir88** [comment]
Ok got it I googled how to run program via gdb but... what exact settings you want for me to set gdb to log? I am not a programmer and a helping hand would be great. I googled that "set logging on" produces gdb.txt file with some logs but not sure if that is what you need to get all important information.

**Comment by aznlir88** [comment]
Ok so I assume no extra settings are required and "set logging on" is all you need.

**Comment by aznlir88** [comment]
Will provide log as soon as I have an opportunity to play unlocked.

**Comment by aznlir88** [comment]
Sorry not playing nfs2 online these days, maybe someone else will have same problem and provide some feedback.
