### ISSUE TITLE
Is there an option to limit framerate to certain frame limit?

### ISSUE THREAD

**Issue by aznlir88** [zaps166/NFSIISE#88]
Is there a possibility to limit framerate to for example 60 FPS? I get best results while recording when I set frame limit to frames i record at and it is also recommended. I looked in the wrapper's config file and cannot find such option.

Is there any way to do it or if now, is there a chance it will get implemented?

**Comment by zaps166** [comment]
You can use OpenGL's V-Sync feature. You change the line `#VSync=-1` to:
- `VSync=1` - it's a regular V-Sync,
- `VSync=2` - it's half of the refresh rate,
- `VSync=3` - it's 1/3 of the refresh rate,

Example: If you have 60 Hz screen and you set VSync to `2`, you'll get 30 FPS.

---

Alternatively you can use external OpenGL frame limiter, e.g. [libstrangle](https://gitlab.com/torkel104/libstrangle) for Linux or [RTSS](https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html) for Windows. `libstrangle` is available in AUR.

**Comment by aznlir88** [comment]
Thanks, VSync solution is just fine I suppose. I am on Linux, but surely not on Arch Linux.
