### ISSUE TITLE
Game odd behaviour after selecting another window or moving virtual desktop

### ISSUE THREAD

**Issue by aznlir88** [zaps166/NFSIISE#89]
Something i noticed just recently I wanted to inform people on Discord about my IP address to join and after returning to game window there was no sound or music and game crashed while loading race. Needed to host again.

But there is more to it, if I want to record gameplay I cannot switch to OBS to select window because when i get back to game same thing happens. I've tried also using key shortcut to move to another virtual desktop and same this is happening. It is happening every time i choose another window or virtual desktop.

I run game in borderless window on linux, using nfs2se-gl2 executable. Not sure if there is any other info I can provide. Switching to another window or virtual desktop just causes it everytime.

**Comment by zaps166** [comment]
Weird, can't reproduce - no crashes here. Maybe something is wrong with that binary. Have you tried to compile it (e.g. from AUR)?

**Comment by aznlir88** [comment]
Well not playing nfs2 these days as short on time but yes, i compiled it myself.

**Comment by zaps166** [comment]
I don't know, can't reproduce. I can just disable minimization events, so audio will not stop playing when it's minimized/on other virtual desktop. Maybe it's already fixed or it was SDL2 or system audio server issue? Or game bug which I can't reproduce.

If you remember how to reproduce and have time, could you check whether it's still crashing?

**Comment by aznlir88** [comment]
Not really playing now but if I happen to play I will let you know, yes. Thank you for looking into it.

**Comment by zaps166** [comment]
Ok, np!

But a different question: isn't it annoying when sound turns off while minimizing or switching desktops?
