### ISSUE TITLE
lower case conversion script should handle file permissions

### ISSUE THREAD

**Issue by random2324** [zaps166/NFSIISE#9]
Hi,
trying to run the game after running the script fails. (again, the error msg box could be more verbose)
The script should also change the permission of the game files, so that you can run the game as standard user.

P.S.
I observe some bad flickering in the upper half of the screen while ingame. Maybe its due mesa radeonsi drivers? Problems go away using windowed mode instead of fullscreen.

**Comment by zaps166** [comment]
Hi!

> trying to run the game after running the script fails

Does it fail on incorrect permissions?

> The script should also change the permission of the game files, so that you can run the game as standard user.

So add `chmod 644` on every file and `chmod 755` on every directory?

> I observe some bad flickering in the upper half of the screen while ingame.

Hmm, maybe a driver issue. Try to disable WM compositing (if enabled). Do you have triple-buffering enabled? And at least you can edit `~/.nfs2se/nfs2se.conf` and uncomment and set `UseGlBleginGlEnd` and try again. I have no problems on NVIDIA proprietary and Intel MESA drivers. With triple-buffering the screen can flicker when game is loading or somewhere in menu, but the game-play is OK.

> again, the error msg box could be more verbose

Which error msg box? About missing `fedata` and `gamedata` dirs? I can't check every necessary file :smile:, so it only checks for these two directories if someone will forgot to add the game data :)

**Comment by zaps166** [comment]
Fixed script, now it also changes file permissions.

**Comment by random2324** [comment]
Yes, correct the the game started as soon as I changed permissions. I didnt test your changes but I guess it works now-Thanks!
If fedata or gamedata is not correctly in place or game cant access them, game gives error msg box on start. So the point is, you dont need to check for every file. But once the game fails to load the game files, give a proper error message to the users.

**Comment by zaps166** [comment]
If `fedata` and/or `gamedata` is missing then it shows the messagebox about missing data. If directories exists it loads the game. If there are missing files from `fedata` the original NFS code can show the messagebox. If files from `gamedata` are missing or if it doesn't have permissions (this I can change about permissions of main directories) then the game crashes (SIGSEGV, bugs in original game), so I must debug and change the assembly code (probably a lot of places there).
