### ISSUE TITLE
Steam deck compile

### ISSUE THREAD

**Issue by Eclipse2025** [zaps166/NFSIISE#90]
Can anyone see about adding in the compile file commands to work on the steam deck? It’s arch Linux from my understanding and several commands are invalid currently. (Yasm being one)
As line 58 is my current stopping point.

**Comment by zaps166** [comment]
I don't have Steam Deck. Could you send error log? Do you use `nfs2se-git` from AUR?

**Comment by Eclipse2025** [comment]
Seems i have to install the yasm via pacman, im in the process of working some things. And will send up the codes once im able

**Comment by HadetTheUndying** [comment]
> Seems i have to install the yasm via pacman, im in the process of working some things. And will send up the codes once im able

Make you're using the lib32 versions of each package. I can write a compile guide in a few days.

**Comment by hmlendea** [comment]
Anyone got it running without removing the write-protection from the partition?

**Comment by hinrik** [comment]
> Anyone got it running without removing the write-protection from the partition?

I had to turn that off the write-protection to install (with pacman) the development dependencies needed for compiling NFSIISE. But you can re-enable the write-proection afterwards.

**Comment by grandtheftoli** [comment]
> > Anyone got it running without removing the write-protection from the partition?
> 
> I had to turn off the write-protection to install (with pacman) the development dependencies needed for compiling NFSIISE. But you can re-enable the write-protection afterwards.

It would be awesome to get a short guide how to do it. I recently got the game with this cool script back to work on Linux mint but it would be even better to run it on my steam deck! :-)

**Comment by zaps166** [comment]
I don't have Steam Deck, but is installing `yasm` and `gcc-multilib` is possible, try this (use it to update, too):

```sh
#!/bin/sh

if [[ ! -e NFSIISE ]]; then
    sudo pacman -Sy --needed gcc-multilib yasm || exit
    git clone https://github.com/zaps166/NFSIISE || exit
fi

cd NFSIISE || exit
git pull || exit
git submodule update --init src/Asm || exit

./compile_nfs || exit
```

When this script finishes, copy `fedata` and `gamedata` into `Need For Speed II SE` and run the game from `Need For Speed II SE`. Use `convert_to_lowercase` script to convert all game files to small letters.

**Comment by HadetTheUndying** [comment]
Honestly I will probably just make a Flatpak this week

**Comment by zaps166** [comment]
Ok, or just use this: https://github.com/zaps166/NFSIISE/releases I'll update it soon, too.
