### ISSUE TITLE
execvp: No such file or directory.

### ISSUE THREAD

**Issue by SimplyTadpole** [zaps166/NFSIISE#95]
I've installed the game alongside the "fedata" and "gamedata" folders taken from the NFS2SE ISO, ran the lowercase script, but attempting to run the game consistently fails: running `nfs2se` (and its gl2 option) through the terminal gives a generic error message about the file being unable to run, while attempting to run them directly from the file browser prints the error message "execvp: no such file or directory".

![image](https://user-images.githubusercontent.com/70490001/217146306-88940317-587c-422a-8fd9-98bb5878890e.png)

Running Fedora Kinoite 37.

**Comment by zaps166** [comment]
Install 32 bit libs.

**Comment by zaps166** [comment]
It happens when you attempt to run 32-bit app on 64-bit OS without 32-bit libs (including glibc).

**Comment by zaps166** [comment]
Does it work? :smile:

**Comment by SimplyTadpole** [comment]
I'm sorry, things came up on my end. Do you know what're the names of the necessary 32-bit lib packages I need to install? Preferably the names for Fedora's packages, but Arch/Debian's are fine too.

**Comment by zaps166** [comment]
On Arch you can install `nfs2se-git` from AUR (use e.g. `yay` AUR client, don't forget to install `base-devel` first).
If you can't execute 32-bit apps, you probably need `lib32-glibc` (Arch pkg name).

**Comment by SimplyTadpole** [comment]
So uh, I couldn't figure out what was the 32-bit package for glibc on Fedora, but I got it to work by running it through Lutris via their native Linux runtime. I guess it packages 32-bit drivers within it? But either way, the game ran just fine. Sorry for bothering you with this ^^'
