### ISSUE TITLE
If i try to start nfs2se.exe Error message: MOVIE FILE NOT FOUND

### ISSUE THREAD

**Issue by etmdevelopeowner** [zaps166/NFSIISE#96]
If i try to start nfs2se.exe Error message: MOVIE FILE NOT FOUND
How To fix IT?

**Comment by zaps166** [comment]
Check your game data if it's NFS 2 SE.
Convert to lower case using script.

**Comment by zaps166** [comment]
`NEED_FOR_SPEED_2__SPECIAL_E` - movies are missing here. Download ISO (bin/cue).
