### ISSUE TITLE
game not running

### ISSUE THREAD

**Issue by muhammadbasitobaid** [zaps166/NFSIISE#97]
Need For Speed II SE
  Wrapper v1.3.0
  Game    v1.1.2
  OpenGL  1
dbus[23832]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

**Comment by zaps166** [comment]
I don't use D-Bus, but maybe SDL2 does. Check your 32-bit libs and SDL2 installation. How did you install it?
